{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "34c6c309",
   "metadata": {},
   "outputs": [],
   "source": [
    "import xarray as xr\n",
    "import pandas as pd\n",
    "import numpy as np\n",
    "import glob\n",
    "import matplotlib.pyplot as plt\n",
    "\n",
    "import glob\n",
    "\n",
    "import cartopy.crs as ccrs\n",
    "import matplotlib.pyplot as plt"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "db423239",
   "metadata": {},
   "source": [
    "# make annual maps for each period"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "ab7d5232",
   "metadata": {},
   "outputs": [],
   "source": [
    "root_path = '/Users/willatobin/Documents/SIO/ClimateBench2/backend/paleo_data_cache'\n",
    "# eocene\n",
    "eocene_models = glob.glob(f'{root_path}/deepmip/dap.ceda.ac.uk/badc/cmip6/data/CMIP6Plus/DeepMIP/deepmip-eocene-p1/*/*/*-x*/*/climatology/*')\n",
    "\n",
    "# pliocene\n",
    "pliocene_models = glob.glob(f'{root_path}/*/midPliocene-eoi400_tas_annual.nc')\n",
    "# lig127k\n",
    "lig127k_models = glob.glob(f'{root_path}/*/lig127k_tas_annual.nc')\n",
    "# LGM\n",
    "lgm_models = glob.glob(f'{root_path}/*/lgm_tas_annual.nc')\n",
    "# midH\n",
    "midHolocene_models = glob.glob(f'{root_path}/*/midHolocene_tas_annual.nc')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "29fd269f",
   "metadata": {},
   "outputs": [],
   "source": [
    "# period = 'eocene'\n",
    "# for file in eocene_models:\n",
    "#     model = file.split('/')[17]\n",
    "#     co2 = file.split('/')[18].split('-')[-1]\n",
    "\n",
    "#     ds = xr.open_dataset(file)\n",
    "    \n",
    "#     if \"t\" in ds.dims:\n",
    "#         ds = ds.rename({'t':'time','latitude':'lat','longitude':'lon'})\n",
    "#     if \"time_counter\" in ds.dims:\n",
    "#         ds = ds.rename({'time_counter':'time'})\n",
    "    \n",
    "#     ds = ds.mean(dim='time')\n",
    "\n",
    "#     fig, axis = plt.subplots(1, 1, figsize=(9,5),subplot_kw=dict(projection=ccrs.Robinson(central_longitude=180)))\n",
    "\n",
    "#     cax = (ds['tas'] - 273.15).plot(\n",
    "#         ax=axis,transform=ccrs.PlateCarree(), \n",
    "#         vmin = -60,\n",
    "#         vmax = 60,\n",
    "#         cmap = 'RdBu_r',\n",
    "#         add_colorbar=False\n",
    "#     )\n",
    "#     cbar = fig.colorbar(cax, ticks=[-60,-30, 0, 30,60])\n",
    "#     axis.coastlines()  # cartopy function\n",
    "\n",
    "#     axis.set_title(f\"{model} CO2{co2}\",fontsize=20)\n",
    "\n",
    "#     os.makedirs(f'results/paleo/{period}_maps',exist_ok=True)\n",
    "#     fig.savefig(f'results/paleo/{period}_maps/{model}_{co2}.png', bbox_inches='tight', pad_inches=0.1)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "c8478718",
   "metadata": {},
   "outputs": [],
   "source": [
    "# period = 'pliocene' # run this for each non eocene period\n",
    "# for file in pliocene_models:\n",
    "#     model = file.split('/')[8]\n",
    "\n",
    "#     ds = xr.open_dataset(file)\n",
    "\n",
    "#     fig, axis = plt.subplots(1, 1, figsize=(9,5),subplot_kw=dict(projection=ccrs.Robinson(central_longitude=180)))\n",
    "\n",
    "#     cax = (ds['tas'] - 273.15).plot(\n",
    "#         ax=axis,transform=ccrs.PlateCarree(), \n",
    "#         vmin = -60,\n",
    "#         vmax = 60,\n",
    "#         cmap = 'RdBu_r',\n",
    "#         add_colorbar=False\n",
    "#     )\n",
    "#     cbar = fig.colorbar(cax, ticks=[-60,-30, 0, 30,60])\n",
    "#     axis.coastlines()  # cartopy function\n",
    "\n",
    "#     axis.set_title(model,fontsize=20)\n",
    "\n",
    "#     os.makedirs(f'results/paleo/{period}_maps',exist_ok=True)\n",
    "#     fig.savefig(f'results/paleo/{period}_maps/{model}.png', bbox_inches='tight', pad_inches=0.1)"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "1cd2797a",
   "metadata": {},
   "source": [
    "for seasonal plots, do zonal means and make csv."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 16,
   "id": "8626505d",
   "metadata": {},
   "outputs": [],
   "source": [
    "df = pd.read_csv(\"https://cmip6.storage.googleapis.com/pangeo-cmip6.csv\")\n",
    "piC_tas_df = df[(df['activity_id'] == 'CMIP') & (df['experiment_id'] == 'piControl')& (df['table_id'] == 'Amon')& (df['variable_id'] == 'tas')]#['table_id'].unique()\n",
    "\n",
    "piC_eocene = glob.glob(f'{root_path}/deepmip/dap.ceda.ac.uk/badc/cmip6/data/CMIP6Plus/DeepMIP/deepmip-eocene-p1/*/*/*-PI/*/climatology/*')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "dc4ef903",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/var/folders/ys/qmftlyyx3dj63021dv4205g80000gn/T/ipykernel_85352/2736516945.py:23: SerializationWarning: Unable to decode time axis into full numpy.datetime64[ns] objects, continuing using cftime.datetime objects instead, reason: dates out of range. To silence this warning use a coarser resolution 'time_unit' or specify 'use_cftime=True'.\n",
      "  piC_ds = xr.open_zarr(piC_tas_df[piC_tas_df['source_id'] == model].iloc[0]['zstore'],chunks={})\n",
      "/var/folders/ys/qmftlyyx3dj63021dv4205g80000gn/T/ipykernel_85352/2736516945.py:23: SerializationWarning: Unable to decode time axis into full numpy.datetime64[ns] objects, continuing using cftime.datetime objects instead, reason: dates out of range. To silence this warning use a coarser resolution 'time_unit' or specify 'use_cftime=True'.\n",
      "  piC_ds = xr.open_zarr(piC_tas_df[piC_tas_df['source_id'] == model].iloc[0]['zstore'],chunks={})\n",
      "/var/folders/ys/qmftlyyx3dj63021dv4205g80000gn/T/ipykernel_85352/2736516945.py:23: SerializationWarning: Unable to decode time axis into full numpy.datetime64 objects, continuing using cftime.datetime objects instead, reason: dates prior reform date (1582-10-15). To silence this warning specify 'use_cftime=True'.\n",
      "  piC_ds = xr.open_zarr(piC_tas_df[piC_tas_df['source_id'] == model].iloc[0]['zstore'],chunks={})\n",
      "/var/folders/ys/qmftlyyx3dj63021dv4205g80000gn/T/ipykernel_85352/2736516945.py:23: SerializationWarning: Unable to decode time axis into full numpy.datetime64 objects, continuing using cftime.datetime objects instead, reason: dates prior reform date (1582-10-15). To silence this warning specify 'use_cftime=True'.\n",
      "  piC_ds = xr.open_zarr(piC_tas_df[piC_tas_df['source_id'] == model].iloc[0]['zstore'],chunks={})\n",
      "/var/folders/ys/qmftlyyx3dj63021dv4205g80000gn/T/ipykernel_85352/2736516945.py:23: SerializationWarning: Unable to decode time axis into full numpy.datetime64[ns] objects, continuing using cftime.datetime objects instead, reason: dates out of range. To silence this warning use a coarser resolution 'time_unit' or specify 'use_cftime=True'.\n",
      "  piC_ds = xr.open_zarr(piC_tas_df[piC_tas_df['source_id'] == model].iloc[0]['zstore'],chunks={})\n",
      "/var/folders/ys/qmftlyyx3dj63021dv4205g80000gn/T/ipykernel_85352/2736516945.py:23: SerializationWarning: Unable to decode time axis into full numpy.datetime64[ns] objects, continuing using cftime.datetime objects instead, reason: dates out of range. To silence this warning use a coarser resolution 'time_unit' or specify 'use_cftime=True'.\n",
      "  piC_ds = xr.open_zarr(piC_tas_df[piC_tas_df['source_id'] == model].iloc[0]['zstore'],chunks={})\n",
      "/var/folders/ys/qmftlyyx3dj63021dv4205g80000gn/T/ipykernel_85352/2736516945.py:23: SerializationWarning: Unable to decode time axis into full numpy.datetime64[ns] objects, continuing using cftime.datetime objects instead, reason: dates out of range. To silence this warning use a coarser resolution 'time_unit' or specify 'use_cftime=True'.\n",
      "  piC_ds = xr.open_zarr(piC_tas_df[piC_tas_df['source_id'] == model].iloc[0]['zstore'],chunks={})\n",
      "/var/folders/ys/qmftlyyx3dj63021dv4205g80000gn/T/ipykernel_85352/2736516945.py:23: SerializationWarning: Unable to decode time axis into full numpy.datetime64[ns] objects, continuing using cftime.datetime objects instead, reason: dates out of range. To silence this warning use a coarser resolution 'time_unit' or specify 'use_cftime=True'.\n",
      "  piC_ds = xr.open_zarr(piC_tas_df[piC_tas_df['source_id'] == model].iloc[0]['zstore'],chunks={})\n",
      "/var/folders/ys/qmftlyyx3dj63021dv4205g80000gn/T/ipykernel_85352/2736516945.py:23: SerializationWarning: Unable to decode time axis into full numpy.datetime64[ns] objects, continuing using cftime.datetime objects instead, reason: dates out of range. To silence this warning use a coarser resolution 'time_unit' or specify 'use_cftime=True'.\n",
      "  piC_ds = xr.open_zarr(piC_tas_df[piC_tas_df['source_id'] == model].iloc[0]['zstore'],chunks={})\n",
      "/var/folders/ys/qmftlyyx3dj63021dv4205g80000gn/T/ipykernel_85352/2736516945.py:23: SerializationWarning: Unable to decode time axis into full numpy.datetime64[ns] objects, continuing using cftime.datetime objects instead, reason: dates out of range. To silence this warning use a coarser resolution 'time_unit' or specify 'use_cftime=True'.\n",
      "  piC_ds = xr.open_zarr(piC_tas_df[piC_tas_df['source_id'] == model].iloc[0]['zstore'],chunks={})\n",
      "/var/folders/ys/qmftlyyx3dj63021dv4205g80000gn/T/ipykernel_85352/2736516945.py:23: SerializationWarning: Unable to decode time axis into full numpy.datetime64[ns] objects, continuing using cftime.datetime objects instead, reason: dates out of range. To silence this warning use a coarser resolution 'time_unit' or specify 'use_cftime=True'.\n",
      "  piC_ds = xr.open_zarr(piC_tas_df[piC_tas_df['source_id'] == model].iloc[0]['zstore'],chunks={})\n",
      "/var/folders/ys/qmftlyyx3dj63021dv4205g80000gn/T/ipykernel_85352/2736516945.py:23: SerializationWarning: Unable to decode time axis into full numpy.datetime64[ns] objects, continuing using cftime.datetime objects instead, reason: dates out of range. To silence this warning use a coarser resolution 'time_unit' or specify 'use_cftime=True'.\n",
      "  piC_ds = xr.open_zarr(piC_tas_df[piC_tas_df['source_id'] == model].iloc[0]['zstore'],chunks={})\n",
      "/var/folders/ys/qmftlyyx3dj63021dv4205g80000gn/T/ipykernel_85352/2736516945.py:23: SerializationWarning: Unable to decode time axis into full numpy.datetime64[ns] objects, continuing using cftime.datetime objects instead, reason: dates out of range. To silence this warning use a coarser resolution 'time_unit' or specify 'use_cftime=True'.\n",
      "  piC_ds = xr.open_zarr(piC_tas_df[piC_tas_df['source_id'] == model].iloc[0]['zstore'],chunks={})\n",
      "/var/folders/ys/qmftlyyx3dj63021dv4205g80000gn/T/ipykernel_85352/2736516945.py:23: SerializationWarning: Unable to decode time axis into full numpy.datetime64[ns] objects, continuing using cftime.datetime objects instead, reason: dates out of range. To silence this warning use a coarser resolution 'time_unit' or specify 'use_cftime=True'.\n",
      "  piC_ds = xr.open_zarr(piC_tas_df[piC_tas_df['source_id'] == model].iloc[0]['zstore'],chunks={})\n",
      "/var/folders/ys/qmftlyyx3dj63021dv4205g80000gn/T/ipykernel_85352/2736516945.py:23: SerializationWarning: Unable to decode time axis into full numpy.datetime64[ns] objects, continuing using cftime.datetime objects instead, reason: dates out of range. To silence this warning use a coarser resolution 'time_unit' or specify 'use_cftime=True'.\n",
      "  piC_ds = xr.open_zarr(piC_tas_df[piC_tas_df['source_id'] == model].iloc[0]['zstore'],chunks={})\n",
      "/var/folders/ys/qmftlyyx3dj63021dv4205g80000gn/T/ipykernel_85352/2736516945.py:23: SerializationWarning: Unable to decode time axis into full numpy.datetime64[ns] objects, continuing using cftime.datetime objects instead, reason: dates out of range. To silence this warning use a coarser resolution 'time_unit' or specify 'use_cftime=True'.\n",
      "  piC_ds = xr.open_zarr(piC_tas_df[piC_tas_df['source_id'] == model].iloc[0]['zstore'],chunks={})\n",
      "/var/folders/ys/qmftlyyx3dj63021dv4205g80000gn/T/ipykernel_85352/2736516945.py:23: SerializationWarning: Unable to decode time axis into full numpy.datetime64[ns] objects, continuing using cftime.datetime objects instead, reason: dates out of range. To silence this warning use a coarser resolution 'time_unit' or specify 'use_cftime=True'.\n",
      "  piC_ds = xr.open_zarr(piC_tas_df[piC_tas_df['source_id'] == model].iloc[0]['zstore'],chunks={})\n",
      "/var/folders/ys/qmftlyyx3dj63021dv4205g80000gn/T/ipykernel_85352/2736516945.py:23: SerializationWarning: Unable to decode time axis into full numpy.datetime64[ns] objects, continuing using cftime.datetime objects instead, reason: dates out of range. To silence this warning use a coarser resolution 'time_unit' or specify 'use_cftime=True'.\n",
      "  piC_ds = xr.open_zarr(piC_tas_df[piC_tas_df['source_id'] == model].iloc[0]['zstore'],chunks={})\n",
      "/var/folders/ys/qmftlyyx3dj63021dv4205g80000gn/T/ipykernel_85352/2736516945.py:23: SerializationWarning: Unable to decode time axis into full numpy.datetime64[ns] objects, continuing using cftime.datetime objects instead, reason: dates out of range. To silence this warning use a coarser resolution 'time_unit' or specify 'use_cftime=True'.\n",
      "  piC_ds = xr.open_zarr(piC_tas_df[piC_tas_df['source_id'] == model].iloc[0]['zstore'],chunks={})\n",
      "/var/folders/ys/qmftlyyx3dj63021dv4205g80000gn/T/ipykernel_85352/2736516945.py:23: SerializationWarning: Unable to decode time axis into full numpy.datetime64[ns] objects, continuing using cftime.datetime objects instead, reason: dates out of range. To silence this warning use a coarser resolution 'time_unit' or specify 'use_cftime=True'.\n",
      "  piC_ds = xr.open_zarr(piC_tas_df[piC_tas_df['source_id'] == model].iloc[0]['zstore'],chunks={})\n",
      "/var/folders/ys/qmftlyyx3dj63021dv4205g80000gn/T/ipykernel_85352/2736516945.py:23: SerializationWarning: Unable to decode time axis into full numpy.datetime64[ns] objects, continuing using cftime.datetime objects instead, reason: dates out of range. To silence this warning use a coarser resolution 'time_unit' or specify 'use_cftime=True'.\n",
      "  piC_ds = xr.open_zarr(piC_tas_df[piC_tas_df['source_id'] == model].iloc[0]['zstore'],chunks={})\n",
      "/var/folders/ys/qmftlyyx3dj63021dv4205g80000gn/T/ipykernel_85352/2736516945.py:23: SerializationWarning: Unable to decode time axis into full numpy.datetime64[ns] objects, continuing using cftime.datetime objects instead, reason: dates out of range. To silence this warning use a coarser resolution 'time_unit' or specify 'use_cftime=True'.\n",
      "  piC_ds = xr.open_zarr(piC_tas_df[piC_tas_df['source_id'] == model].iloc[0]['zstore'],chunks={})\n",
      "/var/folders/ys/qmftlyyx3dj63021dv4205g80000gn/T/ipykernel_85352/2736516945.py:23: SerializationWarning: Unable to decode time axis into full numpy.datetime64[ns] objects, continuing using cftime.datetime objects instead, reason: dates out of range. To silence this warning use a coarser resolution 'time_unit' or specify 'use_cftime=True'.\n",
      "  piC_ds = xr.open_zarr(piC_tas_df[piC_tas_df['source_id'] == model].iloc[0]['zstore'],chunks={})\n",
      "/var/folders/ys/qmftlyyx3dj63021dv4205g80000gn/T/ipykernel_85352/2736516945.py:23: SerializationWarning: Unable to decode time axis into full numpy.datetime64[ns] objects, continuing using cftime.datetime objects instead, reason: dates out of range. To silence this warning use a coarser resolution 'time_unit' or specify 'use_cftime=True'.\n",
      "  piC_ds = xr.open_zarr(piC_tas_df[piC_tas_df['source_id'] == model].iloc[0]['zstore'],chunks={})\n",
      "/var/folders/ys/qmftlyyx3dj63021dv4205g80000gn/T/ipykernel_85352/2736516945.py:23: SerializationWarning: Unable to decode time axis into full numpy.datetime64[ns] objects, continuing using cftime.datetime objects instead, reason: dates out of range. To silence this warning use a coarser resolution 'time_unit' or specify 'use_cftime=True'.\n",
      "  piC_ds = xr.open_zarr(piC_tas_df[piC_tas_df['source_id'] == model].iloc[0]['zstore'],chunks={})\n",
      "/var/folders/ys/qmftlyyx3dj63021dv4205g80000gn/T/ipykernel_85352/2736516945.py:23: SerializationWarning: Unable to decode time axis into full numpy.datetime64[ns] objects, continuing using cftime.datetime objects instead, reason: dates out of range. To silence this warning use a coarser resolution 'time_unit' or specify 'use_cftime=True'.\n",
      "  piC_ds = xr.open_zarr(piC_tas_df[piC_tas_df['source_id'] == model].iloc[0]['zstore'],chunks={})\n",
      "/var/folders/ys/qmftlyyx3dj63021dv4205g80000gn/T/ipykernel_85352/2736516945.py:23: SerializationWarning: Unable to decode time axis into full numpy.datetime64[ns] objects, continuing using cftime.datetime objects instead, reason: dates out of range. To silence this warning use a coarser resolution 'time_unit' or specify 'use_cftime=True'.\n",
      "  piC_ds = xr.open_zarr(piC_tas_df[piC_tas_df['source_id'] == model].iloc[0]['zstore'],chunks={})\n",
      "/var/folders/ys/qmftlyyx3dj63021dv4205g80000gn/T/ipykernel_85352/2736516945.py:23: SerializationWarning: Unable to decode time axis into full numpy.datetime64[ns] objects, continuing using cftime.datetime objects instead, reason: dates out of range. To silence this warning use a coarser resolution 'time_unit' or specify 'use_cftime=True'.\n",
      "  piC_ds = xr.open_zarr(piC_tas_df[piC_tas_df['source_id'] == model].iloc[0]['zstore'],chunks={})\n",
      "/var/folders/ys/qmftlyyx3dj63021dv4205g80000gn/T/ipykernel_85352/2736516945.py:23: SerializationWarning: Unable to decode time axis into full numpy.datetime64[ns] objects, continuing using cftime.datetime objects instead, reason: dates out of range. To silence this warning use a coarser resolution 'time_unit' or specify 'use_cftime=True'.\n",
      "  piC_ds = xr.open_zarr(piC_tas_df[piC_tas_df['source_id'] == model].iloc[0]['zstore'],chunks={})\n",
      "/var/folders/ys/qmftlyyx3dj63021dv4205g80000gn/T/ipykernel_85352/2736516945.py:23: SerializationWarning: Unable to decode time axis into full numpy.datetime64 objects, continuing using cftime.datetime objects instead, reason: dates prior reform date (1582-10-15). To silence this warning specify 'use_cftime=True'.\n",
      "  piC_ds = xr.open_zarr(piC_tas_df[piC_tas_df['source_id'] == model].iloc[0]['zstore'],chunks={})\n",
      "/var/folders/ys/qmftlyyx3dj63021dv4205g80000gn/T/ipykernel_85352/2736516945.py:41: SerializationWarning: Unable to decode time axis into full numpy.datetime64[ns] objects, continuing using cftime.datetime objects instead, reason: dates out of range. To silence this warning use a coarser resolution 'time_unit' or specify 'use_cftime=True'.\n",
      "  ds = xr.open_dataset(file)\n",
      "/var/folders/ys/qmftlyyx3dj63021dv4205g80000gn/T/ipykernel_85352/2736516945.py:41: SerializationWarning: Unable to decode time axis into full numpy.datetime64[ns] objects, continuing using cftime.datetime objects instead, reason: dates out of range. To silence this warning use a coarser resolution 'time_unit' or specify 'use_cftime=True'.\n",
      "  ds = xr.open_dataset(file)\n",
      "/var/folders/ys/qmftlyyx3dj63021dv4205g80000gn/T/ipykernel_85352/2736516945.py:41: SerializationWarning: Unable to decode time axis into full numpy.datetime64[ns] objects, continuing using cftime.datetime objects instead, reason: dates out of range. To silence this warning use a coarser resolution 'time_unit' or specify 'use_cftime=True'.\n",
      "  ds = xr.open_dataset(file)\n",
      "/var/folders/ys/qmftlyyx3dj63021dv4205g80000gn/T/ipykernel_85352/2736516945.py:41: SerializationWarning: Unable to decode time axis into full numpy.datetime64[ns] objects, continuing using cftime.datetime objects instead, reason: dates out of range. To silence this warning use a coarser resolution 'time_unit' or specify 'use_cftime=True'.\n",
      "  ds = xr.open_dataset(file)\n",
      "/var/folders/ys/qmftlyyx3dj63021dv4205g80000gn/T/ipykernel_85352/2736516945.py:41: SerializationWarning: Unable to decode time axis into full numpy.datetime64[ns] objects, continuing using cftime.datetime objects instead, reason: dates out of range. To silence this warning use a coarser resolution 'time_unit' or specify 'use_cftime=True'.\n",
      "  ds = xr.open_dataset(file)\n",
      "/var/folders/ys/qmftlyyx3dj63021dv4205g80000gn/T/ipykernel_85352/2736516945.py:41: SerializationWarning: Unable to decode time axis into full numpy.datetime64[ns] objects, continuing using cftime.datetime objects instead, reason: dates out of range. To silence this warning use a coarser resolution 'time_unit' or specify 'use_cftime=True'.\n",
      "  ds = xr.open_dataset(file)\n",
      "/var/folders/ys/qmftlyyx3dj63021dv4205g80000gn/T/ipykernel_85352/2736516945.py:41: SerializationWarning: Unable to decode time axis into full numpy.datetime64[ns] objects, continuing using cftime.datetime objects instead, reason: dates out of range. To silence this warning use a coarser resolution 'time_unit' or specify 'use_cftime=True'.\n",
      "  ds = xr.open_dataset(file)\n",
      "/var/folders/ys/qmftlyyx3dj63021dv4205g80000gn/T/ipykernel_85352/2736516945.py:41: SerializationWarning: Unable to decode time axis into full numpy.datetime64[ns] objects, continuing using cftime.datetime objects instead, reason: dates out of range. To silence this warning use a coarser resolution 'time_unit' or specify 'use_cftime=True'.\n",
      "  ds = xr.open_dataset(file)\n",
      "/var/folders/ys/qmftlyyx3dj63021dv4205g80000gn/T/ipykernel_85352/2736516945.py:41: SerializationWarning: Unable to decode time axis into full numpy.datetime64[ns] objects, continuing using cftime.datetime objects instead, reason: dates out of range. To silence this warning use a coarser resolution 'time_unit' or specify 'use_cftime=True'.\n",
      "  ds = xr.open_dataset(file)\n",
      "/var/folders/ys/qmftlyyx3dj63021dv4205g80000gn/T/ipykernel_85352/2736516945.py:41: SerializationWarning: Unable to decode time axis into full numpy.datetime64[ns] objects, continuing using cftime.datetime objects instead, reason: dates out of range. To silence this warning use a coarser resolution 'time_unit' or specify 'use_cftime=True'.\n",
      "  ds = xr.open_dataset(file)\n",
      "/var/folders/ys/qmftlyyx3dj63021dv4205g80000gn/T/ipykernel_85352/2736516945.py:41: SerializationWarning: Unable to decode time axis into full numpy.datetime64[ns] objects, continuing using cftime.datetime objects instead, reason: dates out of range. To silence this warning use a coarser resolution 'time_unit' or specify 'use_cftime=True'.\n",
      "  ds = xr.open_dataset(file)\n",
      "/var/folders/ys/qmftlyyx3dj63021dv4205g80000gn/T/ipykernel_85352/2736516945.py:42: SerializationWarning: Unable to decode time axis into full numpy.datetime64[ns] objects, continuing using cftime.datetime objects instead, reason: dates out of range. To silence this warning use a coarser resolution 'time_unit' or specify 'use_cftime=True'.\n",
      "  ds_pi = xr.open_dataset(pi_file[0])\n",
      "/var/folders/ys/qmftlyyx3dj63021dv4205g80000gn/T/ipykernel_85352/2736516945.py:41: SerializationWarning: Unable to decode time axis into full numpy.datetime64[ns] objects, continuing using cftime.datetime objects instead, reason: dates out of range. To silence this warning use a coarser resolution 'time_unit' or specify 'use_cftime=True'.\n",
      "  ds = xr.open_dataset(file)\n",
      "/var/folders/ys/qmftlyyx3dj63021dv4205g80000gn/T/ipykernel_85352/2736516945.py:41: SerializationWarning: Unable to decode time axis into full numpy.datetime64[ns] objects, continuing using cftime.datetime objects instead, reason: dates out of range. To silence this warning use a coarser resolution 'time_unit' or specify 'use_cftime=True'.\n",
      "  ds = xr.open_dataset(file)\n",
      "/var/folders/ys/qmftlyyx3dj63021dv4205g80000gn/T/ipykernel_85352/2736516945.py:41: SerializationWarning: Unable to decode time axis into full numpy.datetime64[ns] objects, continuing using cftime.datetime objects instead, reason: dates out of range. To silence this warning use a coarser resolution 'time_unit' or specify 'use_cftime=True'.\n",
      "  ds = xr.open_dataset(file)\n",
      "/var/folders/ys/qmftlyyx3dj63021dv4205g80000gn/T/ipykernel_85352/2736516945.py:41: SerializationWarning: Unable to decode time axis into full numpy.datetime64[ns] objects, continuing using cftime.datetime objects instead, reason: dates out of range. To silence this warning use a coarser resolution 'time_unit' or specify 'use_cftime=True'.\n",
      "  ds = xr.open_dataset(file)\n",
      "/var/folders/ys/qmftlyyx3dj63021dv4205g80000gn/T/ipykernel_85352/2736516945.py:41: SerializationWarning: Unable to decode time axis into full numpy.datetime64[ns] objects, continuing using cftime.datetime objects instead, reason: dates out of range. To silence this warning use a coarser resolution 'time_unit' or specify 'use_cftime=True'.\n",
      "  ds = xr.open_dataset(file)\n",
      "/var/folders/ys/qmftlyyx3dj63021dv4205g80000gn/T/ipykernel_85352/2736516945.py:41: SerializationWarning: Unable to decode time axis into full numpy.datetime64[ns] objects, continuing using cftime.datetime objects instead, reason: dates out of range. To silence this warning use a coarser resolution 'time_unit' or specify 'use_cftime=True'.\n",
      "  ds = xr.open_dataset(file)\n",
      "/var/folders/ys/qmftlyyx3dj63021dv4205g80000gn/T/ipykernel_85352/2736516945.py:41: SerializationWarning: Unable to decode time axis into full numpy.datetime64[ns] objects, continuing using cftime.datetime objects instead, reason: dates out of range. To silence this warning use a coarser resolution 'time_unit' or specify 'use_cftime=True'.\n",
      "  ds = xr.open_dataset(file)\n",
      "/var/folders/ys/qmftlyyx3dj63021dv4205g80000gn/T/ipykernel_85352/2736516945.py:41: SerializationWarning: Unable to decode time axis into full numpy.datetime64[ns] objects, continuing using cftime.datetime objects instead, reason: dates out of range. To silence this warning use a coarser resolution 'time_unit' or specify 'use_cftime=True'.\n",
      "  ds = xr.open_dataset(file)\n",
      "/var/folders/ys/qmftlyyx3dj63021dv4205g80000gn/T/ipykernel_85352/2736516945.py:41: SerializationWarning: Unable to decode time axis into full numpy.datetime64[ns] objects, continuing using cftime.datetime objects instead, reason: dates out of range. To silence this warning use a coarser resolution 'time_unit' or specify 'use_cftime=True'.\n",
      "  ds = xr.open_dataset(file)\n",
      "/var/folders/ys/qmftlyyx3dj63021dv4205g80000gn/T/ipykernel_85352/2736516945.py:23: SerializationWarning: Unable to decode time axis into full numpy.datetime64[ns] objects, continuing using cftime.datetime objects instead, reason: dates out of range. To silence this warning use a coarser resolution 'time_unit' or specify 'use_cftime=True'.\n",
      "  piC_ds = xr.open_zarr(piC_tas_df[piC_tas_df['source_id'] == model].iloc[0]['zstore'],chunks={})\n",
      "/var/folders/ys/qmftlyyx3dj63021dv4205g80000gn/T/ipykernel_85352/2736516945.py:23: SerializationWarning: Unable to decode time axis into full numpy.datetime64[ns] objects, continuing using cftime.datetime objects instead, reason: dates out of range. To silence this warning use a coarser resolution 'time_unit' or specify 'use_cftime=True'.\n",
      "  piC_ds = xr.open_zarr(piC_tas_df[piC_tas_df['source_id'] == model].iloc[0]['zstore'],chunks={})\n",
      "/var/folders/ys/qmftlyyx3dj63021dv4205g80000gn/T/ipykernel_85352/2736516945.py:23: SerializationWarning: Unable to decode time axis into full numpy.datetime64 objects, continuing using cftime.datetime objects instead, reason: dates prior reform date (1582-10-15). To silence this warning specify 'use_cftime=True'.\n",
      "  piC_ds = xr.open_zarr(piC_tas_df[piC_tas_df['source_id'] == model].iloc[0]['zstore'],chunks={})\n",
      "/var/folders/ys/qmftlyyx3dj63021dv4205g80000gn/T/ipykernel_85352/2736516945.py:23: SerializationWarning: Unable to decode time axis into full numpy.datetime64 objects, continuing using cftime.datetime objects instead, reason: dates prior reform date (1582-10-15). To silence this warning specify 'use_cftime=True'.\n",
      "  piC_ds = xr.open_zarr(piC_tas_df[piC_tas_df['source_id'] == model].iloc[0]['zstore'],chunks={})\n",
      "/var/folders/ys/qmftlyyx3dj63021dv4205g80000gn/T/ipykernel_85352/2736516945.py:23: SerializationWarning: Unable to decode time axis into full numpy.datetime64[ns] objects, continuing using cftime.datetime objects instead, reason: dates out of range. To silence this warning use a coarser resolution 'time_unit' or specify 'use_cftime=True'.\n",
      "  piC_ds = xr.open_zarr(piC_tas_df[piC_tas_df['source_id'] == model].iloc[0]['zstore'],chunks={})\n",
      "/var/folders/ys/qmftlyyx3dj63021dv4205g80000gn/T/ipykernel_85352/2736516945.py:23: SerializationWarning: Unable to decode time axis into full numpy.datetime64[ns] objects, continuing using cftime.datetime objects instead, reason: dates out of range. To silence this warning use a coarser resolution 'time_unit' or specify 'use_cftime=True'.\n",
      "  piC_ds = xr.open_zarr(piC_tas_df[piC_tas_df['source_id'] == model].iloc[0]['zstore'],chunks={})\n",
      "/var/folders/ys/qmftlyyx3dj63021dv4205g80000gn/T/ipykernel_85352/2736516945.py:23: SerializationWarning: Unable to decode time axis into full numpy.datetime64[ns] objects, continuing using cftime.datetime objects instead, reason: dates out of range. To silence this warning use a coarser resolution 'time_unit' or specify 'use_cftime=True'.\n",
      "  piC_ds = xr.open_zarr(piC_tas_df[piC_tas_df['source_id'] == model].iloc[0]['zstore'],chunks={})\n",
      "/var/folders/ys/qmftlyyx3dj63021dv4205g80000gn/T/ipykernel_85352/2736516945.py:23: SerializationWarning: Unable to decode time axis into full numpy.datetime64[ns] objects, continuing using cftime.datetime objects instead, reason: dates out of range. To silence this warning use a coarser resolution 'time_unit' or specify 'use_cftime=True'.\n",
      "  piC_ds = xr.open_zarr(piC_tas_df[piC_tas_df['source_id'] == model].iloc[0]['zstore'],chunks={})\n",
      "/var/folders/ys/qmftlyyx3dj63021dv4205g80000gn/T/ipykernel_85352/2736516945.py:23: SerializationWarning: Unable to decode time axis into full numpy.datetime64[ns] objects, continuing using cftime.datetime objects instead, reason: dates out of range. To silence this warning use a coarser resolution 'time_unit' or specify 'use_cftime=True'.\n",
      "  piC_ds = xr.open_zarr(piC_tas_df[piC_tas_df['source_id'] == model].iloc[0]['zstore'],chunks={})\n",
      "/var/folders/ys/qmftlyyx3dj63021dv4205g80000gn/T/ipykernel_85352/2736516945.py:23: SerializationWarning: Unable to decode time axis into full numpy.datetime64[ns] objects, continuing using cftime.datetime objects instead, reason: dates out of range. To silence this warning use a coarser resolution 'time_unit' or specify 'use_cftime=True'.\n",
      "  piC_ds = xr.open_zarr(piC_tas_df[piC_tas_df['source_id'] == model].iloc[0]['zstore'],chunks={})\n",
      "/var/folders/ys/qmftlyyx3dj63021dv4205g80000gn/T/ipykernel_85352/2736516945.py:23: SerializationWarning: Unable to decode time axis into full numpy.datetime64[ns] objects, continuing using cftime.datetime objects instead, reason: dates out of range. To silence this warning use a coarser resolution 'time_unit' or specify 'use_cftime=True'.\n",
      "  piC_ds = xr.open_zarr(piC_tas_df[piC_tas_df['source_id'] == model].iloc[0]['zstore'],chunks={})\n",
      "/var/folders/ys/qmftlyyx3dj63021dv4205g80000gn/T/ipykernel_85352/2736516945.py:23: SerializationWarning: Unable to decode time axis into full numpy.datetime64[ns] objects, continuing using cftime.datetime objects instead, reason: dates out of range. To silence this warning use a coarser resolution 'time_unit' or specify 'use_cftime=True'.\n",
      "  piC_ds = xr.open_zarr(piC_tas_df[piC_tas_df['source_id'] == model].iloc[0]['zstore'],chunks={})\n",
      "/var/folders/ys/qmftlyyx3dj63021dv4205g80000gn/T/ipykernel_85352/2736516945.py:23: SerializationWarning: Unable to decode time axis into full numpy.datetime64[ns] objects, continuing using cftime.datetime objects instead, reason: dates out of range. To silence this warning use a coarser resolution 'time_unit' or specify 'use_cftime=True'.\n",
      "  piC_ds = xr.open_zarr(piC_tas_df[piC_tas_df['source_id'] == model].iloc[0]['zstore'],chunks={})\n",
      "/var/folders/ys/qmftlyyx3dj63021dv4205g80000gn/T/ipykernel_85352/2736516945.py:23: SerializationWarning: Unable to decode time axis into full numpy.datetime64[ns] objects, continuing using cftime.datetime objects instead, reason: dates out of range. To silence this warning use a coarser resolution 'time_unit' or specify 'use_cftime=True'.\n",
      "  piC_ds = xr.open_zarr(piC_tas_df[piC_tas_df['source_id'] == model].iloc[0]['zstore'],chunks={})\n",
      "/var/folders/ys/qmftlyyx3dj63021dv4205g80000gn/T/ipykernel_85352/2736516945.py:23: SerializationWarning: Unable to decode time axis into full numpy.datetime64[ns] objects, continuing using cftime.datetime objects instead, reason: dates out of range. To silence this warning use a coarser resolution 'time_unit' or specify 'use_cftime=True'.\n",
      "  piC_ds = xr.open_zarr(piC_tas_df[piC_tas_df['source_id'] == model].iloc[0]['zstore'],chunks={})\n",
      "/var/folders/ys/qmftlyyx3dj63021dv4205g80000gn/T/ipykernel_85352/2736516945.py:23: SerializationWarning: Unable to decode time axis into full numpy.datetime64[ns] objects, continuing using cftime.datetime objects instead, reason: dates out of range. To silence this warning use a coarser resolution 'time_unit' or specify 'use_cftime=True'.\n",
      "  piC_ds = xr.open_zarr(piC_tas_df[piC_tas_df['source_id'] == model].iloc[0]['zstore'],chunks={})\n",
      "/var/folders/ys/qmftlyyx3dj63021dv4205g80000gn/T/ipykernel_85352/2736516945.py:23: SerializationWarning: Unable to decode time axis into full numpy.datetime64[ns] objects, continuing using cftime.datetime objects instead, reason: dates out of range. To silence this warning use a coarser resolution 'time_unit' or specify 'use_cftime=True'.\n",
      "  piC_ds = xr.open_zarr(piC_tas_df[piC_tas_df['source_id'] == model].iloc[0]['zstore'],chunks={})\n",
      "/var/folders/ys/qmftlyyx3dj63021dv4205g80000gn/T/ipykernel_85352/2736516945.py:23: SerializationWarning: Unable to decode time axis into full numpy.datetime64[ns] objects, continuing using cftime.datetime objects instead, reason: dates out of range. To silence this warning use a coarser resolution 'time_unit' or specify 'use_cftime=True'.\n",
      "  piC_ds = xr.open_zarr(piC_tas_df[piC_tas_df['source_id'] == model].iloc[0]['zstore'],chunks={})\n",
      "/var/folders/ys/qmftlyyx3dj63021dv4205g80000gn/T/ipykernel_85352/2736516945.py:23: SerializationWarning: Unable to decode time axis into full numpy.datetime64[ns] objects, continuing using cftime.datetime objects instead, reason: dates out of range. To silence this warning use a coarser resolution 'time_unit' or specify 'use_cftime=True'.\n",
      "  piC_ds = xr.open_zarr(piC_tas_df[piC_tas_df['source_id'] == model].iloc[0]['zstore'],chunks={})\n",
      "/var/folders/ys/qmftlyyx3dj63021dv4205g80000gn/T/ipykernel_85352/2736516945.py:23: SerializationWarning: Unable to decode time axis into full numpy.datetime64[ns] objects, continuing using cftime.datetime objects instead, reason: dates out of range. To silence this warning use a coarser resolution 'time_unit' or specify 'use_cftime=True'.\n",
      "  piC_ds = xr.open_zarr(piC_tas_df[piC_tas_df['source_id'] == model].iloc[0]['zstore'],chunks={})\n",
      "/var/folders/ys/qmftlyyx3dj63021dv4205g80000gn/T/ipykernel_85352/2736516945.py:23: SerializationWarning: Unable to decode time axis into full numpy.datetime64[ns] objects, continuing using cftime.datetime objects instead, reason: dates out of range. To silence this warning use a coarser resolution 'time_unit' or specify 'use_cftime=True'.\n",
      "  piC_ds = xr.open_zarr(piC_tas_df[piC_tas_df['source_id'] == model].iloc[0]['zstore'],chunks={})\n",
      "/var/folders/ys/qmftlyyx3dj63021dv4205g80000gn/T/ipykernel_85352/2736516945.py:23: SerializationWarning: Unable to decode time axis into full numpy.datetime64[ns] objects, continuing using cftime.datetime objects instead, reason: dates out of range. To silence this warning use a coarser resolution 'time_unit' or specify 'use_cftime=True'.\n",
      "  piC_ds = xr.open_zarr(piC_tas_df[piC_tas_df['source_id'] == model].iloc[0]['zstore'],chunks={})\n",
      "/var/folders/ys/qmftlyyx3dj63021dv4205g80000gn/T/ipykernel_85352/2736516945.py:23: SerializationWarning: Unable to decode time axis into full numpy.datetime64[ns] objects, continuing using cftime.datetime objects instead, reason: dates out of range. To silence this warning use a coarser resolution 'time_unit' or specify 'use_cftime=True'.\n",
      "  piC_ds = xr.open_zarr(piC_tas_df[piC_tas_df['source_id'] == model].iloc[0]['zstore'],chunks={})\n",
      "/var/folders/ys/qmftlyyx3dj63021dv4205g80000gn/T/ipykernel_85352/2736516945.py:23: SerializationWarning: Unable to decode time axis into full numpy.datetime64[ns] objects, continuing using cftime.datetime objects instead, reason: dates out of range. To silence this warning use a coarser resolution 'time_unit' or specify 'use_cftime=True'.\n",
      "  piC_ds = xr.open_zarr(piC_tas_df[piC_tas_df['source_id'] == model].iloc[0]['zstore'],chunks={})\n",
      "/var/folders/ys/qmftlyyx3dj63021dv4205g80000gn/T/ipykernel_85352/2736516945.py:23: SerializationWarning: Unable to decode time axis into full numpy.datetime64[ns] objects, continuing using cftime.datetime objects instead, reason: dates out of range. To silence this warning use a coarser resolution 'time_unit' or specify 'use_cftime=True'.\n",
      "  piC_ds = xr.open_zarr(piC_tas_df[piC_tas_df['source_id'] == model].iloc[0]['zstore'],chunks={})\n",
      "/var/folders/ys/qmftlyyx3dj63021dv4205g80000gn/T/ipykernel_85352/2736516945.py:23: SerializationWarning: Unable to decode time axis into full numpy.datetime64[ns] objects, continuing using cftime.datetime objects instead, reason: dates out of range. To silence this warning use a coarser resolution 'time_unit' or specify 'use_cftime=True'.\n",
      "  piC_ds = xr.open_zarr(piC_tas_df[piC_tas_df['source_id'] == model].iloc[0]['zstore'],chunks={})\n",
      "/var/folders/ys/qmftlyyx3dj63021dv4205g80000gn/T/ipykernel_85352/2736516945.py:23: SerializationWarning: Unable to decode time axis into full numpy.datetime64[ns] objects, continuing using cftime.datetime objects instead, reason: dates out of range. To silence this warning use a coarser resolution 'time_unit' or specify 'use_cftime=True'.\n",
      "  piC_ds = xr.open_zarr(piC_tas_df[piC_tas_df['source_id'] == model].iloc[0]['zstore'],chunks={})\n",
      "/var/folders/ys/qmftlyyx3dj63021dv4205g80000gn/T/ipykernel_85352/2736516945.py:23: SerializationWarning: Unable to decode time axis into full numpy.datetime64[ns] objects, continuing using cftime.datetime objects instead, reason: dates out of range. To silence this warning use a coarser resolution 'time_unit' or specify 'use_cftime=True'.\n",
      "  piC_ds = xr.open_zarr(piC_tas_df[piC_tas_df['source_id'] == model].iloc[0]['zstore'],chunks={})\n",
      "/var/folders/ys/qmftlyyx3dj63021dv4205g80000gn/T/ipykernel_85352/2736516945.py:23: SerializationWarning: Unable to decode time axis into full numpy.datetime64[ns] objects, continuing using cftime.datetime objects instead, reason: dates out of range. To silence this warning use a coarser resolution 'time_unit' or specify 'use_cftime=True'.\n",
      "  piC_ds = xr.open_zarr(piC_tas_df[piC_tas_df['source_id'] == model].iloc[0]['zstore'],chunks={})\n",
      "/var/folders/ys/qmftlyyx3dj63021dv4205g80000gn/T/ipykernel_85352/2736516945.py:23: SerializationWarning: Unable to decode time axis into full numpy.datetime64 objects, continuing using cftime.datetime objects instead, reason: dates prior reform date (1582-10-15). To silence this warning specify 'use_cftime=True'.\n",
      "  piC_ds = xr.open_zarr(piC_tas_df[piC_tas_df['source_id'] == model].iloc[0]['zstore'],chunks={})\n",
      "/var/folders/ys/qmftlyyx3dj63021dv4205g80000gn/T/ipykernel_85352/2736516945.py:41: SerializationWarning: Unable to decode time axis into full numpy.datetime64[ns] objects, continuing using cftime.datetime objects instead, reason: dates out of range. To silence this warning use a coarser resolution 'time_unit' or specify 'use_cftime=True'.\n",
      "  ds = xr.open_dataset(file)\n",
      "/var/folders/ys/qmftlyyx3dj63021dv4205g80000gn/T/ipykernel_85352/2736516945.py:41: SerializationWarning: Unable to decode time axis into full numpy.datetime64[ns] objects, continuing using cftime.datetime objects instead, reason: dates out of range. To silence this warning use a coarser resolution 'time_unit' or specify 'use_cftime=True'.\n",
      "  ds = xr.open_dataset(file)\n",
      "/var/folders/ys/qmftlyyx3dj63021dv4205g80000gn/T/ipykernel_85352/2736516945.py:41: SerializationWarning: Unable to decode time axis into full numpy.datetime64[ns] objects, continuing using cftime.datetime objects instead, reason: dates out of range. To silence this warning use a coarser resolution 'time_unit' or specify 'use_cftime=True'.\n",
      "  ds = xr.open_dataset(file)\n",
      "/var/folders/ys/qmftlyyx3dj63021dv4205g80000gn/T/ipykernel_85352/2736516945.py:41: SerializationWarning: Unable to decode time axis into full numpy.datetime64[ns] objects, continuing using cftime.datetime objects instead, reason: dates out of range. To silence this warning use a coarser resolution 'time_unit' or specify 'use_cftime=True'.\n",
      "  ds = xr.open_dataset(file)\n",
      "/var/folders/ys/qmftlyyx3dj63021dv4205g80000gn/T/ipykernel_85352/2736516945.py:41: SerializationWarning: Unable to decode time axis into full numpy.datetime64[ns] objects, continuing using cftime.datetime objects instead, reason: dates out of range. To silence this warning use a coarser resolution 'time_unit' or specify 'use_cftime=True'.\n",
      "  ds = xr.open_dataset(file)\n",
      "/var/folders/ys/qmftlyyx3dj63021dv4205g80000gn/T/ipykernel_85352/2736516945.py:41: SerializationWarning: Unable to decode time axis into full numpy.datetime64[ns] objects, continuing using cftime.datetime objects instead, reason: dates out of range. To silence this warning use a coarser resolution 'time_unit' or specify 'use_cftime=True'.\n",
      "  ds = xr.open_dataset(file)\n",
      "/var/folders/ys/qmftlyyx3dj63021dv4205g80000gn/T/ipykernel_85352/2736516945.py:41: SerializationWarning: Unable to decode time axis into full numpy.datetime64[ns] objects, continuing using cftime.datetime objects instead, reason: dates out of range. To silence this warning use a coarser resolution 'time_unit' or specify 'use_cftime=True'.\n",
      "  ds = xr.open_dataset(file)\n",
      "/var/folders/ys/qmftlyyx3dj63021dv4205g80000gn/T/ipykernel_85352/2736516945.py:41: SerializationWarning: Unable to decode time axis into full numpy.datetime64[ns] objects, continuing using cftime.datetime objects instead, reason: dates out of range. To silence this warning use a coarser resolution 'time_unit' or specify 'use_cftime=True'.\n",
      "  ds = xr.open_dataset(file)\n",
      "/var/folders/ys/qmftlyyx3dj63021dv4205g80000gn/T/ipykernel_85352/2736516945.py:41: SerializationWarning: Unable to decode time axis into full numpy.datetime64[ns] objects, continuing using cftime.datetime objects instead, reason: dates out of range. To silence this warning use a coarser resolution 'time_unit' or specify 'use_cftime=True'.\n",
      "  ds = xr.open_dataset(file)\n",
      "/var/folders/ys/qmftlyyx3dj63021dv4205g80000gn/T/ipykernel_85352/2736516945.py:41: SerializationWarning: Unable to decode time axis into full numpy.datetime64[ns] objects, continuing using cftime.datetime objects instead, reason: dates out of range. To silence this warning use a coarser resolution 'time_unit' or specify 'use_cftime=True'.\n",
      "  ds = xr.open_dataset(file)\n",
      "/var/folders/ys/qmftlyyx3dj63021dv4205g80000gn/T/ipykernel_85352/2736516945.py:41: SerializationWarning: Unable to decode time axis into full numpy.datetime64[ns] objects, continuing using cftime.datetime objects instead, reason: dates out of range. To silence this warning use a coarser resolution 'time_unit' or specify 'use_cftime=True'.\n",
      "  ds = xr.open_dataset(file)\n",
      "/var/folders/ys/qmftlyyx3dj63021dv4205g80000gn/T/ipykernel_85352/2736516945.py:42: SerializationWarning: Unable to decode time axis into full numpy.datetime64[ns] objects, continuing using cftime.datetime objects instead, reason: dates out of range. To silence this warning use a coarser resolution 'time_unit' or specify 'use_cftime=True'.\n",
      "  ds_pi = xr.open_dataset(pi_file[0])\n",
      "/var/folders/ys/qmftlyyx3dj63021dv4205g80000gn/T/ipykernel_85352/2736516945.py:41: SerializationWarning: Unable to decode time axis into full numpy.datetime64[ns] objects, continuing using cftime.datetime objects instead, reason: dates out of range. To silence this warning use a coarser resolution 'time_unit' or specify 'use_cftime=True'.\n",
      "  ds = xr.open_dataset(file)\n",
      "/var/folders/ys/qmftlyyx3dj63021dv4205g80000gn/T/ipykernel_85352/2736516945.py:41: SerializationWarning: Unable to decode time axis into full numpy.datetime64[ns] objects, continuing using cftime.datetime objects instead, reason: dates out of range. To silence this warning use a coarser resolution 'time_unit' or specify 'use_cftime=True'.\n",
      "  ds = xr.open_dataset(file)\n",
      "/var/folders/ys/qmftlyyx3dj63021dv4205g80000gn/T/ipykernel_85352/2736516945.py:41: SerializationWarning: Unable to decode time axis into full numpy.datetime64[ns] objects, continuing using cftime.datetime objects instead, reason: dates out of range. To silence this warning use a coarser resolution 'time_unit' or specify 'use_cftime=True'.\n",
      "  ds = xr.open_dataset(file)\n",
      "/var/folders/ys/qmftlyyx3dj63021dv4205g80000gn/T/ipykernel_85352/2736516945.py:41: SerializationWarning: Unable to decode time axis into full numpy.datetime64[ns] objects, continuing using cftime.datetime objects instead, reason: dates out of range. To silence this warning use a coarser resolution 'time_unit' or specify 'use_cftime=True'.\n",
      "  ds = xr.open_dataset(file)\n",
      "/var/folders/ys/qmftlyyx3dj63021dv4205g80000gn/T/ipykernel_85352/2736516945.py:41: SerializationWarning: Unable to decode time axis into full numpy.datetime64[ns] objects, continuing using cftime.datetime objects instead, reason: dates out of range. To silence this warning use a coarser resolution 'time_unit' or specify 'use_cftime=True'.\n",
      "  ds = xr.open_dataset(file)\n",
      "/var/folders/ys/qmftlyyx3dj63021dv4205g80000gn/T/ipykernel_85352/2736516945.py:41: SerializationWarning: Unable to decode time axis into full numpy.datetime64[ns] objects, continuing using cftime.datetime objects instead, reason: dates out of range. To silence this warning use a coarser resolution 'time_unit' or specify 'use_cftime=True'.\n",
      "  ds = xr.open_dataset(file)\n",
      "/var/folders/ys/qmftlyyx3dj63021dv4205g80000gn/T/ipykernel_85352/2736516945.py:41: SerializationWarning: Unable to decode time axis into full numpy.datetime64[ns] objects, continuing using cftime.datetime objects instead, reason: dates out of range. To silence this warning use a coarser resolution 'time_unit' or specify 'use_cftime=True'.\n",
      "  ds = xr.open_dataset(file)\n",
      "/var/folders/ys/qmftlyyx3dj63021dv4205g80000gn/T/ipykernel_85352/2736516945.py:41: SerializationWarning: Unable to decode time axis into full numpy.datetime64[ns] objects, continuing using cftime.datetime objects instead, reason: dates out of range. To silence this warning use a coarser resolution 'time_unit' or specify 'use_cftime=True'.\n",
      "  ds = xr.open_dataset(file)\n",
      "/var/folders/ys/qmftlyyx3dj63021dv4205g80000gn/T/ipykernel_85352/2736516945.py:41: SerializationWarning: Unable to decode time axis into full numpy.datetime64[ns] objects, continuing using cftime.datetime objects instead, reason: dates out of range. To silence this warning use a coarser resolution 'time_unit' or specify 'use_cftime=True'.\n",
      "  ds = xr.open_dataset(file)\n",
      "/var/folders/ys/qmftlyyx3dj63021dv4205g80000gn/T/ipykernel_85352/2736516945.py:23: SerializationWarning: Unable to decode time axis into full numpy.datetime64[ns] objects, continuing using cftime.datetime objects instead, reason: dates out of range. To silence this warning use a coarser resolution 'time_unit' or specify 'use_cftime=True'.\n",
      "  piC_ds = xr.open_zarr(piC_tas_df[piC_tas_df['source_id'] == model].iloc[0]['zstore'],chunks={})\n",
      "/var/folders/ys/qmftlyyx3dj63021dv4205g80000gn/T/ipykernel_85352/2736516945.py:23: SerializationWarning: Unable to decode time axis into full numpy.datetime64[ns] objects, continuing using cftime.datetime objects instead, reason: dates out of range. To silence this warning use a coarser resolution 'time_unit' or specify 'use_cftime=True'.\n",
      "  piC_ds = xr.open_zarr(piC_tas_df[piC_tas_df['source_id'] == model].iloc[0]['zstore'],chunks={})\n",
      "/var/folders/ys/qmftlyyx3dj63021dv4205g80000gn/T/ipykernel_85352/2736516945.py:23: SerializationWarning: Unable to decode time axis into full numpy.datetime64 objects, continuing using cftime.datetime objects instead, reason: dates prior reform date (1582-10-15). To silence this warning specify 'use_cftime=True'.\n",
      "  piC_ds = xr.open_zarr(piC_tas_df[piC_tas_df['source_id'] == model].iloc[0]['zstore'],chunks={})\n",
      "/var/folders/ys/qmftlyyx3dj63021dv4205g80000gn/T/ipykernel_85352/2736516945.py:23: SerializationWarning: Unable to decode time axis into full numpy.datetime64 objects, continuing using cftime.datetime objects instead, reason: dates prior reform date (1582-10-15). To silence this warning specify 'use_cftime=True'.\n",
      "  piC_ds = xr.open_zarr(piC_tas_df[piC_tas_df['source_id'] == model].iloc[0]['zstore'],chunks={})\n",
      "/var/folders/ys/qmftlyyx3dj63021dv4205g80000gn/T/ipykernel_85352/2736516945.py:23: SerializationWarning: Unable to decode time axis into full numpy.datetime64[ns] objects, continuing using cftime.datetime objects instead, reason: dates out of range. To silence this warning use a coarser resolution 'time_unit' or specify 'use_cftime=True'.\n",
      "  piC_ds = xr.open_zarr(piC_tas_df[piC_tas_df['source_id'] == model].iloc[0]['zstore'],chunks={})\n",
      "/var/folders/ys/qmftlyyx3dj63021dv4205g80000gn/T/ipykernel_85352/2736516945.py:23: SerializationWarning: Unable to decode time axis into full numpy.datetime64[ns] objects, continuing using cftime.datetime objects instead, reason: dates out of range. To silence this warning use a coarser resolution 'time_unit' or specify 'use_cftime=True'.\n",
      "  piC_ds = xr.open_zarr(piC_tas_df[piC_tas_df['source_id'] == model].iloc[0]['zstore'],chunks={})\n",
      "/var/folders/ys/qmftlyyx3dj63021dv4205g80000gn/T/ipykernel_85352/2736516945.py:23: SerializationWarning: Unable to decode time axis into full numpy.datetime64[ns] objects, continuing using cftime.datetime objects instead, reason: dates out of range. To silence this warning use a coarser resolution 'time_unit' or specify 'use_cftime=True'.\n",
      "  piC_ds = xr.open_zarr(piC_tas_df[piC_tas_df['source_id'] == model].iloc[0]['zstore'],chunks={})\n",
      "/var/folders/ys/qmftlyyx3dj63021dv4205g80000gn/T/ipykernel_85352/2736516945.py:23: SerializationWarning: Unable to decode time axis into full numpy.datetime64[ns] objects, continuing using cftime.datetime objects instead, reason: dates out of range. To silence this warning use a coarser resolution 'time_unit' or specify 'use_cftime=True'.\n",
      "  piC_ds = xr.open_zarr(piC_tas_df[piC_tas_df['source_id'] == model].iloc[0]['zstore'],chunks={})\n",
      "/var/folders/ys/qmftlyyx3dj63021dv4205g80000gn/T/ipykernel_85352/2736516945.py:23: SerializationWarning: Unable to decode time axis into full numpy.datetime64[ns] objects, continuing using cftime.datetime objects instead, reason: dates out of range. To silence this warning use a coarser resolution 'time_unit' or specify 'use_cftime=True'.\n",
      "  piC_ds = xr.open_zarr(piC_tas_df[piC_tas_df['source_id'] == model].iloc[0]['zstore'],chunks={})\n",
      "/var/folders/ys/qmftlyyx3dj63021dv4205g80000gn/T/ipykernel_85352/2736516945.py:23: SerializationWarning: Unable to decode time axis into full numpy.datetime64[ns] objects, continuing using cftime.datetime objects instead, reason: dates out of range. To silence this warning use a coarser resolution 'time_unit' or specify 'use_cftime=True'.\n",
      "  piC_ds = xr.open_zarr(piC_tas_df[piC_tas_df['source_id'] == model].iloc[0]['zstore'],chunks={})\n",
      "/var/folders/ys/qmftlyyx3dj63021dv4205g80000gn/T/ipykernel_85352/2736516945.py:23: SerializationWarning: Unable to decode time axis into full numpy.datetime64[ns] objects, continuing using cftime.datetime objects instead, reason: dates out of range. To silence this warning use a coarser resolution 'time_unit' or specify 'use_cftime=True'.\n",
      "  piC_ds = xr.open_zarr(piC_tas_df[piC_tas_df['source_id'] == model].iloc[0]['zstore'],chunks={})\n",
      "/var/folders/ys/qmftlyyx3dj63021dv4205g80000gn/T/ipykernel_85352/2736516945.py:23: SerializationWarning: Unable to decode time axis into full numpy.datetime64[ns] objects, continuing using cftime.datetime objects instead, reason: dates out of range. To silence this warning use a coarser resolution 'time_unit' or specify 'use_cftime=True'.\n",
      "  piC_ds = xr.open_zarr(piC_tas_df[piC_tas_df['source_id'] == model].iloc[0]['zstore'],chunks={})\n",
      "/var/folders/ys/qmftlyyx3dj63021dv4205g80000gn/T/ipykernel_85352/2736516945.py:23: SerializationWarning: Unable to decode time axis into full numpy.datetime64[ns] objects, continuing using cftime.datetime objects instead, reason: dates out of range. To silence this warning use a coarser resolution 'time_unit' or specify 'use_cftime=True'.\n",
      "  piC_ds = xr.open_zarr(piC_tas_df[piC_tas_df['source_id'] == model].iloc[0]['zstore'],chunks={})\n",
      "/var/folders/ys/qmftlyyx3dj63021dv4205g80000gn/T/ipykernel_85352/2736516945.py:23: SerializationWarning: Unable to decode time axis into full numpy.datetime64[ns] objects, continuing using cftime.datetime objects instead, reason: dates out of range. To silence this warning use a coarser resolution 'time_unit' or specify 'use_cftime=True'.\n",
      "  piC_ds = xr.open_zarr(piC_tas_df[piC_tas_df['source_id'] == model].iloc[0]['zstore'],chunks={})\n",
      "/var/folders/ys/qmftlyyx3dj63021dv4205g80000gn/T/ipykernel_85352/2736516945.py:23: SerializationWarning: Unable to decode time axis into full numpy.datetime64[ns] objects, continuing using cftime.datetime objects instead, reason: dates out of range. To silence this warning use a coarser resolution 'time_unit' or specify 'use_cftime=True'.\n",
      "  piC_ds = xr.open_zarr(piC_tas_df[piC_tas_df['source_id'] == model].iloc[0]['zstore'],chunks={})\n",
      "/var/folders/ys/qmftlyyx3dj63021dv4205g80000gn/T/ipykernel_85352/2736516945.py:23: SerializationWarning: Unable to decode time axis into full numpy.datetime64[ns] objects, continuing using cftime.datetime objects instead, reason: dates out of range. To silence this warning use a coarser resolution 'time_unit' or specify 'use_cftime=True'.\n",
      "  piC_ds = xr.open_zarr(piC_tas_df[piC_tas_df['source_id'] == model].iloc[0]['zstore'],chunks={})\n",
      "/var/folders/ys/qmftlyyx3dj63021dv4205g80000gn/T/ipykernel_85352/2736516945.py:23: SerializationWarning: Unable to decode time axis into full numpy.datetime64[ns] objects, continuing using cftime.datetime objects instead, reason: dates out of range. To silence this warning use a coarser resolution 'time_unit' or specify 'use_cftime=True'.\n",
      "  piC_ds = xr.open_zarr(piC_tas_df[piC_tas_df['source_id'] == model].iloc[0]['zstore'],chunks={})\n",
      "/var/folders/ys/qmftlyyx3dj63021dv4205g80000gn/T/ipykernel_85352/2736516945.py:23: SerializationWarning: Unable to decode time axis into full numpy.datetime64[ns] objects, continuing using cftime.datetime objects instead, reason: dates out of range. To silence this warning use a coarser resolution 'time_unit' or specify 'use_cftime=True'.\n",
      "  piC_ds = xr.open_zarr(piC_tas_df[piC_tas_df['source_id'] == model].iloc[0]['zstore'],chunks={})\n",
      "/var/folders/ys/qmftlyyx3dj63021dv4205g80000gn/T/ipykernel_85352/2736516945.py:23: SerializationWarning: Unable to decode time axis into full numpy.datetime64[ns] objects, continuing using cftime.datetime objects instead, reason: dates out of range. To silence this warning use a coarser resolution 'time_unit' or specify 'use_cftime=True'.\n",
      "  piC_ds = xr.open_zarr(piC_tas_df[piC_tas_df['source_id'] == model].iloc[0]['zstore'],chunks={})\n",
      "/var/folders/ys/qmftlyyx3dj63021dv4205g80000gn/T/ipykernel_85352/2736516945.py:23: SerializationWarning: Unable to decode time axis into full numpy.datetime64[ns] objects, continuing using cftime.datetime objects instead, reason: dates out of range. To silence this warning use a coarser resolution 'time_unit' or specify 'use_cftime=True'.\n",
      "  piC_ds = xr.open_zarr(piC_tas_df[piC_tas_df['source_id'] == model].iloc[0]['zstore'],chunks={})\n",
      "/var/folders/ys/qmftlyyx3dj63021dv4205g80000gn/T/ipykernel_85352/2736516945.py:23: SerializationWarning: Unable to decode time axis into full numpy.datetime64[ns] objects, continuing using cftime.datetime objects instead, reason: dates out of range. To silence this warning use a coarser resolution 'time_unit' or specify 'use_cftime=True'.\n",
      "  piC_ds = xr.open_zarr(piC_tas_df[piC_tas_df['source_id'] == model].iloc[0]['zstore'],chunks={})\n",
      "/var/folders/ys/qmftlyyx3dj63021dv4205g80000gn/T/ipykernel_85352/2736516945.py:23: SerializationWarning: Unable to decode time axis into full numpy.datetime64[ns] objects, continuing using cftime.datetime objects instead, reason: dates out of range. To silence this warning use a coarser resolution 'time_unit' or specify 'use_cftime=True'.\n",
      "  piC_ds = xr.open_zarr(piC_tas_df[piC_tas_df['source_id'] == model].iloc[0]['zstore'],chunks={})\n",
      "/var/folders/ys/qmftlyyx3dj63021dv4205g80000gn/T/ipykernel_85352/2736516945.py:23: SerializationWarning: Unable to decode time axis into full numpy.datetime64[ns] objects, continuing using cftime.datetime objects instead, reason: dates out of range. To silence this warning use a coarser resolution 'time_unit' or specify 'use_cftime=True'.\n",
      "  piC_ds = xr.open_zarr(piC_tas_df[piC_tas_df['source_id'] == model].iloc[0]['zstore'],chunks={})\n",
      "/var/folders/ys/qmftlyyx3dj63021dv4205g80000gn/T/ipykernel_85352/2736516945.py:23: SerializationWarning: Unable to decode time axis into full numpy.datetime64[ns] objects, continuing using cftime.datetime objects instead, reason: dates out of range. To silence this warning use a coarser resolution 'time_unit' or specify 'use_cftime=True'.\n",
      "  piC_ds = xr.open_zarr(piC_tas_df[piC_tas_df['source_id'] == model].iloc[0]['zstore'],chunks={})\n",
      "/var/folders/ys/qmftlyyx3dj63021dv4205g80000gn/T/ipykernel_85352/2736516945.py:23: SerializationWarning: Unable to decode time axis into full numpy.datetime64[ns] objects, continuing using cftime.datetime objects instead, reason: dates out of range. To silence this warning use a coarser resolution 'time_unit' or specify 'use_cftime=True'.\n",
      "  piC_ds = xr.open_zarr(piC_tas_df[piC_tas_df['source_id'] == model].iloc[0]['zstore'],chunks={})\n",
      "/var/folders/ys/qmftlyyx3dj63021dv4205g80000gn/T/ipykernel_85352/2736516945.py:23: SerializationWarning: Unable to decode time axis into full numpy.datetime64[ns] objects, continuing using cftime.datetime objects instead, reason: dates out of range. To silence this warning use a coarser resolution 'time_unit' or specify 'use_cftime=True'.\n",
      "  piC_ds = xr.open_zarr(piC_tas_df[piC_tas_df['source_id'] == model].iloc[0]['zstore'],chunks={})\n",
      "/var/folders/ys/qmftlyyx3dj63021dv4205g80000gn/T/ipykernel_85352/2736516945.py:23: SerializationWarning: Unable to decode time axis into full numpy.datetime64[ns] objects, continuing using cftime.datetime objects instead, reason: dates out of range. To silence this warning use a coarser resolution 'time_unit' or specify 'use_cftime=True'.\n",
      "  piC_ds = xr.open_zarr(piC_tas_df[piC_tas_df['source_id'] == model].iloc[0]['zstore'],chunks={})\n",
      "/var/folders/ys/qmftlyyx3dj63021dv4205g80000gn/T/ipykernel_85352/2736516945.py:23: SerializationWarning: Unable to decode time axis into full numpy.datetime64[ns] objects, continuing using cftime.datetime objects instead, reason: dates out of range. To silence this warning use a coarser resolution 'time_unit' or specify 'use_cftime=True'.\n",
      "  piC_ds = xr.open_zarr(piC_tas_df[piC_tas_df['source_id'] == model].iloc[0]['zstore'],chunks={})\n",
      "/var/folders/ys/qmftlyyx3dj63021dv4205g80000gn/T/ipykernel_85352/2736516945.py:23: SerializationWarning: Unable to decode time axis into full numpy.datetime64[ns] objects, continuing using cftime.datetime objects instead, reason: dates out of range. To silence this warning use a coarser resolution 'time_unit' or specify 'use_cftime=True'.\n",
      "  piC_ds = xr.open_zarr(piC_tas_df[piC_tas_df['source_id'] == model].iloc[0]['zstore'],chunks={})\n",
      "/var/folders/ys/qmftlyyx3dj63021dv4205g80000gn/T/ipykernel_85352/2736516945.py:23: SerializationWarning: Unable to decode time axis into full numpy.datetime64 objects, continuing using cftime.datetime objects instead, reason: dates prior reform date (1582-10-15). To silence this warning specify 'use_cftime=True'.\n",
      "  piC_ds = xr.open_zarr(piC_tas_df[piC_tas_df['source_id'] == model].iloc[0]['zstore'],chunks={})\n",
      "/var/folders/ys/qmftlyyx3dj63021dv4205g80000gn/T/ipykernel_85352/2736516945.py:41: SerializationWarning: Unable to decode time axis into full numpy.datetime64[ns] objects, continuing using cftime.datetime objects instead, reason: dates out of range. To silence this warning use a coarser resolution 'time_unit' or specify 'use_cftime=True'.\n",
      "  ds = xr.open_dataset(file)\n",
      "/var/folders/ys/qmftlyyx3dj63021dv4205g80000gn/T/ipykernel_85352/2736516945.py:41: SerializationWarning: Unable to decode time axis into full numpy.datetime64[ns] objects, continuing using cftime.datetime objects instead, reason: dates out of range. To silence this warning use a coarser resolution 'time_unit' or specify 'use_cftime=True'.\n",
      "  ds = xr.open_dataset(file)\n",
      "/var/folders/ys/qmftlyyx3dj63021dv4205g80000gn/T/ipykernel_85352/2736516945.py:41: SerializationWarning: Unable to decode time axis into full numpy.datetime64[ns] objects, continuing using cftime.datetime objects instead, reason: dates out of range. To silence this warning use a coarser resolution 'time_unit' or specify 'use_cftime=True'.\n",
      "  ds = xr.open_dataset(file)\n",
      "/var/folders/ys/qmftlyyx3dj63021dv4205g80000gn/T/ipykernel_85352/2736516945.py:41: SerializationWarning: Unable to decode time axis into full numpy.datetime64[ns] objects, continuing using cftime.datetime objects instead, reason: dates out of range. To silence this warning use a coarser resolution 'time_unit' or specify 'use_cftime=True'.\n",
      "  ds = xr.open_dataset(file)\n",
      "/var/folders/ys/qmftlyyx3dj63021dv4205g80000gn/T/ipykernel_85352/2736516945.py:41: SerializationWarning: Unable to decode time axis into full numpy.datetime64[ns] objects, continuing using cftime.datetime objects instead, reason: dates out of range. To silence this warning use a coarser resolution 'time_unit' or specify 'use_cftime=True'.\n",
      "  ds = xr.open_dataset(file)\n",
      "/var/folders/ys/qmftlyyx3dj63021dv4205g80000gn/T/ipykernel_85352/2736516945.py:41: SerializationWarning: Unable to decode time axis into full numpy.datetime64[ns] objects, continuing using cftime.datetime objects instead, reason: dates out of range. To silence this warning use a coarser resolution 'time_unit' or specify 'use_cftime=True'.\n",
      "  ds = xr.open_dataset(file)\n",
      "/var/folders/ys/qmftlyyx3dj63021dv4205g80000gn/T/ipykernel_85352/2736516945.py:41: SerializationWarning: Unable to decode time axis into full numpy.datetime64[ns] objects, continuing using cftime.datetime objects instead, reason: dates out of range. To silence this warning use a coarser resolution 'time_unit' or specify 'use_cftime=True'.\n",
      "  ds = xr.open_dataset(file)\n",
      "/var/folders/ys/qmftlyyx3dj63021dv4205g80000gn/T/ipykernel_85352/2736516945.py:41: SerializationWarning: Unable to decode time axis into full numpy.datetime64[ns] objects, continuing using cftime.datetime objects instead, reason: dates out of range. To silence this warning use a coarser resolution 'time_unit' or specify 'use_cftime=True'.\n",
      "  ds = xr.open_dataset(file)\n",
      "/var/folders/ys/qmftlyyx3dj63021dv4205g80000gn/T/ipykernel_85352/2736516945.py:41: SerializationWarning: Unable to decode time axis into full numpy.datetime64[ns] objects, continuing using cftime.datetime objects instead, reason: dates out of range. To silence this warning use a coarser resolution 'time_unit' or specify 'use_cftime=True'.\n",
      "  ds = xr.open_dataset(file)\n",
      "/var/folders/ys/qmftlyyx3dj63021dv4205g80000gn/T/ipykernel_85352/2736516945.py:41: SerializationWarning: Unable to decode time axis into full numpy.datetime64[ns] objects, continuing using cftime.datetime objects instead, reason: dates out of range. To silence this warning use a coarser resolution 'time_unit' or specify 'use_cftime=True'.\n",
      "  ds = xr.open_dataset(file)\n",
      "/var/folders/ys/qmftlyyx3dj63021dv4205g80000gn/T/ipykernel_85352/2736516945.py:41: SerializationWarning: Unable to decode time axis into full numpy.datetime64[ns] objects, continuing using cftime.datetime objects instead, reason: dates out of range. To silence this warning use a coarser resolution 'time_unit' or specify 'use_cftime=True'.\n",
      "  ds = xr.open_dataset(file)\n",
      "/var/folders/ys/qmftlyyx3dj63021dv4205g80000gn/T/ipykernel_85352/2736516945.py:42: SerializationWarning: Unable to decode time axis into full numpy.datetime64[ns] objects, continuing using cftime.datetime objects instead, reason: dates out of range. To silence this warning use a coarser resolution 'time_unit' or specify 'use_cftime=True'.\n",
      "  ds_pi = xr.open_dataset(pi_file[0])\n",
      "/var/folders/ys/qmftlyyx3dj63021dv4205g80000gn/T/ipykernel_85352/2736516945.py:41: SerializationWarning: Unable to decode time axis into full numpy.datetime64[ns] objects, continuing using cftime.datetime objects instead, reason: dates out of range. To silence this warning use a coarser resolution 'time_unit' or specify 'use_cftime=True'.\n",
      "  ds = xr.open_dataset(file)\n",
      "/var/folders/ys/qmftlyyx3dj63021dv4205g80000gn/T/ipykernel_85352/2736516945.py:41: SerializationWarning: Unable to decode time axis into full numpy.datetime64[ns] objects, continuing using cftime.datetime objects instead, reason: dates out of range. To silence this warning use a coarser resolution 'time_unit' or specify 'use_cftime=True'.\n",
      "  ds = xr.open_dataset(file)\n",
      "/var/folders/ys/qmftlyyx3dj63021dv4205g80000gn/T/ipykernel_85352/2736516945.py:41: SerializationWarning: Unable to decode time axis into full numpy.datetime64[ns] objects, continuing using cftime.datetime objects instead, reason: dates out of range. To silence this warning use a coarser resolution 'time_unit' or specify 'use_cftime=True'.\n",
      "  ds = xr.open_dataset(file)\n",
      "/var/folders/ys/qmftlyyx3dj63021dv4205g80000gn/T/ipykernel_85352/2736516945.py:41: SerializationWarning: Unable to decode time axis into full numpy.datetime64[ns] objects, continuing using cftime.datetime objects instead, reason: dates out of range. To silence this warning use a coarser resolution 'time_unit' or specify 'use_cftime=True'.\n",
      "  ds = xr.open_dataset(file)\n",
      "/var/folders/ys/qmftlyyx3dj63021dv4205g80000gn/T/ipykernel_85352/2736516945.py:41: SerializationWarning: Unable to decode time axis into full numpy.datetime64[ns] objects, continuing using cftime.datetime objects instead, reason: dates out of range. To silence this warning use a coarser resolution 'time_unit' or specify 'use_cftime=True'.\n",
      "  ds = xr.open_dataset(file)\n",
      "/var/folders/ys/qmftlyyx3dj63021dv4205g80000gn/T/ipykernel_85352/2736516945.py:41: SerializationWarning: Unable to decode time axis into full numpy.datetime64[ns] objects, continuing using cftime.datetime objects instead, reason: dates out of range. To silence this warning use a coarser resolution 'time_unit' or specify 'use_cftime=True'.\n",
      "  ds = xr.open_dataset(file)\n",
      "/var/folders/ys/qmftlyyx3dj63021dv4205g80000gn/T/ipykernel_85352/2736516945.py:41: SerializationWarning: Unable to decode time axis into full numpy.datetime64[ns] objects, continuing using cftime.datetime objects instead, reason: dates out of range. To silence this warning use a coarser resolution 'time_unit' or specify 'use_cftime=True'.\n",
      "  ds = xr.open_dataset(file)\n",
      "/var/folders/ys/qmftlyyx3dj63021dv4205g80000gn/T/ipykernel_85352/2736516945.py:41: SerializationWarning: Unable to decode time axis into full numpy.datetime64[ns] objects, continuing using cftime.datetime objects instead, reason: dates out of range. To silence this warning use a coarser resolution 'time_unit' or specify 'use_cftime=True'.\n",
      "  ds = xr.open_dataset(file)\n",
      "/var/folders/ys/qmftlyyx3dj63021dv4205g80000gn/T/ipykernel_85352/2736516945.py:41: SerializationWarning: Unable to decode time axis into full numpy.datetime64[ns] objects, continuing using cftime.datetime objects instead, reason: dates out of range. To silence this warning use a coarser resolution 'time_unit' or specify 'use_cftime=True'.\n",
      "  ds = xr.open_dataset(file)\n",
      "/var/folders/ys/qmftlyyx3dj63021dv4205g80000gn/T/ipykernel_85352/2736516945.py:23: SerializationWarning: Unable to decode time axis into full numpy.datetime64[ns] objects, continuing using cftime.datetime objects instead, reason: dates out of range. To silence this warning use a coarser resolution 'time_unit' or specify 'use_cftime=True'.\n",
      "  piC_ds = xr.open_zarr(piC_tas_df[piC_tas_df['source_id'] == model].iloc[0]['zstore'],chunks={})\n",
      "/var/folders/ys/qmftlyyx3dj63021dv4205g80000gn/T/ipykernel_85352/2736516945.py:23: SerializationWarning: Unable to decode time axis into full numpy.datetime64[ns] objects, continuing using cftime.datetime objects instead, reason: dates out of range. To silence this warning use a coarser resolution 'time_unit' or specify 'use_cftime=True'.\n",
      "  piC_ds = xr.open_zarr(piC_tas_df[piC_tas_df['source_id'] == model].iloc[0]['zstore'],chunks={})\n",
      "/var/folders/ys/qmftlyyx3dj63021dv4205g80000gn/T/ipykernel_85352/2736516945.py:23: SerializationWarning: Unable to decode time axis into full numpy.datetime64 objects, continuing using cftime.datetime objects instead, reason: dates prior reform date (1582-10-15). To silence this warning specify 'use_cftime=True'.\n",
      "  piC_ds = xr.open_zarr(piC_tas_df[piC_tas_df['source_id'] == model].iloc[0]['zstore'],chunks={})\n",
      "/var/folders/ys/qmftlyyx3dj63021dv4205g80000gn/T/ipykernel_85352/2736516945.py:23: SerializationWarning: Unable to decode time axis into full numpy.datetime64 objects, continuing using cftime.datetime objects instead, reason: dates prior reform date (1582-10-15). To silence this warning specify 'use_cftime=True'.\n",
      "  piC_ds = xr.open_zarr(piC_tas_df[piC_tas_df['source_id'] == model].iloc[0]['zstore'],chunks={})\n",
      "/var/folders/ys/qmftlyyx3dj63021dv4205g80000gn/T/ipykernel_85352/2736516945.py:23: SerializationWarning: Unable to decode time axis into full numpy.datetime64[ns] objects, continuing using cftime.datetime objects instead, reason: dates out of range. To silence this warning use a coarser resolution 'time_unit' or specify 'use_cftime=True'.\n",
      "  piC_ds = xr.open_zarr(piC_tas_df[piC_tas_df['source_id'] == model].iloc[0]['zstore'],chunks={})\n",
      "/var/folders/ys/qmftlyyx3dj63021dv4205g80000gn/T/ipykernel_85352/2736516945.py:23: SerializationWarning: Unable to decode time axis into full numpy.datetime64[ns] objects, continuing using cftime.datetime objects instead, reason: dates out of range. To silence this warning use a coarser resolution 'time_unit' or specify 'use_cftime=True'.\n",
      "  piC_ds = xr.open_zarr(piC_tas_df[piC_tas_df['source_id'] == model].iloc[0]['zstore'],chunks={})\n",
      "/var/folders/ys/qmftlyyx3dj63021dv4205g80000gn/T/ipykernel_85352/2736516945.py:23: SerializationWarning: Unable to decode time axis into full numpy.datetime64[ns] objects, continuing using cftime.datetime objects instead, reason: dates out of range. To silence this warning use a coarser resolution 'time_unit' or specify 'use_cftime=True'.\n",
      "  piC_ds = xr.open_zarr(piC_tas_df[piC_tas_df['source_id'] == model].iloc[0]['zstore'],chunks={})\n",
      "/var/folders/ys/qmftlyyx3dj63021dv4205g80000gn/T/ipykernel_85352/2736516945.py:23: SerializationWarning: Unable to decode time axis into full numpy.datetime64[ns] objects, continuing using cftime.datetime objects instead, reason: dates out of range. To silence this warning use a coarser resolution 'time_unit' or specify 'use_cftime=True'.\n",
      "  piC_ds = xr.open_zarr(piC_tas_df[piC_tas_df['source_id'] == model].iloc[0]['zstore'],chunks={})\n",
      "/var/folders/ys/qmftlyyx3dj63021dv4205g80000gn/T/ipykernel_85352/2736516945.py:23: SerializationWarning: Unable to decode time axis into full numpy.datetime64[ns] objects, continuing using cftime.datetime objects instead, reason: dates out of range. To silence this warning use a coarser resolution 'time_unit' or specify 'use_cftime=True'.\n",
      "  piC_ds = xr.open_zarr(piC_tas_df[piC_tas_df['source_id'] == model].iloc[0]['zstore'],chunks={})\n",
      "/var/folders/ys/qmftlyyx3dj63021dv4205g80000gn/T/ipykernel_85352/2736516945.py:23: SerializationWarning: Unable to decode time axis into full numpy.datetime64[ns] objects, continuing using cftime.datetime objects instead, reason: dates out of range. To silence this warning use a coarser resolution 'time_unit' or specify 'use_cftime=True'.\n",
      "  piC_ds = xr.open_zarr(piC_tas_df[piC_tas_df['source_id'] == model].iloc[0]['zstore'],chunks={})\n",
      "/var/folders/ys/qmftlyyx3dj63021dv4205g80000gn/T/ipykernel_85352/2736516945.py:23: SerializationWarning: Unable to decode time axis into full numpy.datetime64[ns] objects, continuing using cftime.datetime objects instead, reason: dates out of range. To silence this warning use a coarser resolution 'time_unit' or specify 'use_cftime=True'.\n",
      "  piC_ds = xr.open_zarr(piC_tas_df[piC_tas_df['source_id'] == model].iloc[0]['zstore'],chunks={})\n",
      "/var/folders/ys/qmftlyyx3dj63021dv4205g80000gn/T/ipykernel_85352/2736516945.py:23: SerializationWarning: Unable to decode time axis into full numpy.datetime64[ns] objects, continuing using cftime.datetime objects instead, reason: dates out of range. To silence this warning use a coarser resolution 'time_unit' or specify 'use_cftime=True'.\n",
      "  piC_ds = xr.open_zarr(piC_tas_df[piC_tas_df['source_id'] == model].iloc[0]['zstore'],chunks={})\n",
      "/var/folders/ys/qmftlyyx3dj63021dv4205g80000gn/T/ipykernel_85352/2736516945.py:23: SerializationWarning: Unable to decode time axis into full numpy.datetime64[ns] objects, continuing using cftime.datetime objects instead, reason: dates out of range. To silence this warning use a coarser resolution 'time_unit' or specify 'use_cftime=True'.\n",
      "  piC_ds = xr.open_zarr(piC_tas_df[piC_tas_df['source_id'] == model].iloc[0]['zstore'],chunks={})\n",
      "/var/folders/ys/qmftlyyx3dj63021dv4205g80000gn/T/ipykernel_85352/2736516945.py:23: SerializationWarning: Unable to decode time axis into full numpy.datetime64[ns] objects, continuing using cftime.datetime objects instead, reason: dates out of range. To silence this warning use a coarser resolution 'time_unit' or specify 'use_cftime=True'.\n",
      "  piC_ds = xr.open_zarr(piC_tas_df[piC_tas_df['source_id'] == model].iloc[0]['zstore'],chunks={})\n",
      "/var/folders/ys/qmftlyyx3dj63021dv4205g80000gn/T/ipykernel_85352/2736516945.py:23: SerializationWarning: Unable to decode time axis into full numpy.datetime64[ns] objects, continuing using cftime.datetime objects instead, reason: dates out of range. To silence this warning use a coarser resolution 'time_unit' or specify 'use_cftime=True'.\n",
      "  piC_ds = xr.open_zarr(piC_tas_df[piC_tas_df['source_id'] == model].iloc[0]['zstore'],chunks={})\n",
      "/var/folders/ys/qmftlyyx3dj63021dv4205g80000gn/T/ipykernel_85352/2736516945.py:23: SerializationWarning: Unable to decode time axis into full numpy.datetime64[ns] objects, continuing using cftime.datetime objects instead, reason: dates out of range. To silence this warning use a coarser resolution 'time_unit' or specify 'use_cftime=True'.\n",
      "  piC_ds = xr.open_zarr(piC_tas_df[piC_tas_df['source_id'] == model].iloc[0]['zstore'],chunks={})\n",
      "/var/folders/ys/qmftlyyx3dj63021dv4205g80000gn/T/ipykernel_85352/2736516945.py:23: SerializationWarning: Unable to decode time axis into full numpy.datetime64[ns] objects, continuing using cftime.datetime objects instead, reason: dates out of range. To silence this warning use a coarser resolution 'time_unit' or specify 'use_cftime=True'.\n",
      "  piC_ds = xr.open_zarr(piC_tas_df[piC_tas_df['source_id'] == model].iloc[0]['zstore'],chunks={})\n",
      "/var/folders/ys/qmftlyyx3dj63021dv4205g80000gn/T/ipykernel_85352/2736516945.py:23: SerializationWarning: Unable to decode time axis into full numpy.datetime64[ns] objects, continuing using cftime.datetime objects instead, reason: dates out of range. To silence this warning use a coarser resolution 'time_unit' or specify 'use_cftime=True'.\n",
      "  piC_ds = xr.open_zarr(piC_tas_df[piC_tas_df['source_id'] == model].iloc[0]['zstore'],chunks={})\n",
      "/var/folders/ys/qmftlyyx3dj63021dv4205g80000gn/T/ipykernel_85352/2736516945.py:23: SerializationWarning: Unable to decode time axis into full numpy.datetime64[ns] objects, continuing using cftime.datetime objects instead, reason: dates out of range. To silence this warning use a coarser resolution 'time_unit' or specify 'use_cftime=True'.\n",
      "  piC_ds = xr.open_zarr(piC_tas_df[piC_tas_df['source_id'] == model].iloc[0]['zstore'],chunks={})\n",
      "/var/folders/ys/qmftlyyx3dj63021dv4205g80000gn/T/ipykernel_85352/2736516945.py:23: SerializationWarning: Unable to decode time axis into full numpy.datetime64[ns] objects, continuing using cftime.datetime objects instead, reason: dates out of range. To silence this warning use a coarser resolution 'time_unit' or specify 'use_cftime=True'.\n",
      "  piC_ds = xr.open_zarr(piC_tas_df[piC_tas_df['source_id'] == model].iloc[0]['zstore'],chunks={})\n",
      "/var/folders/ys/qmftlyyx3dj63021dv4205g80000gn/T/ipykernel_85352/2736516945.py:23: SerializationWarning: Unable to decode time axis into full numpy.datetime64[ns] objects, continuing using cftime.datetime objects instead, reason: dates out of range. To silence this warning use a coarser resolution 'time_unit' or specify 'use_cftime=True'.\n",
      "  piC_ds = xr.open_zarr(piC_tas_df[piC_tas_df['source_id'] == model].iloc[0]['zstore'],chunks={})\n",
      "/var/folders/ys/qmftlyyx3dj63021dv4205g80000gn/T/ipykernel_85352/2736516945.py:23: SerializationWarning: Unable to decode time axis into full numpy.datetime64[ns] objects, continuing using cftime.datetime objects instead, reason: dates out of range. To silence this warning use a coarser resolution 'time_unit' or specify 'use_cftime=True'.\n",
      "  piC_ds = xr.open_zarr(piC_tas_df[piC_tas_df['source_id'] == model].iloc[0]['zstore'],chunks={})\n",
      "/var/folders/ys/qmftlyyx3dj63021dv4205g80000gn/T/ipykernel_85352/2736516945.py:23: SerializationWarning: Unable to decode time axis into full numpy.datetime64[ns] objects, continuing using cftime.datetime objects instead, reason: dates out of range. To silence this warning use a coarser resolution 'time_unit' or specify 'use_cftime=True'.\n",
      "  piC_ds = xr.open_zarr(piC_tas_df[piC_tas_df['source_id'] == model].iloc[0]['zstore'],chunks={})\n",
      "/var/folders/ys/qmftlyyx3dj63021dv4205g80000gn/T/ipykernel_85352/2736516945.py:23: SerializationWarning: Unable to decode time axis into full numpy.datetime64[ns] objects, continuing using cftime.datetime objects instead, reason: dates out of range. To silence this warning use a coarser resolution 'time_unit' or specify 'use_cftime=True'.\n",
      "  piC_ds = xr.open_zarr(piC_tas_df[piC_tas_df['source_id'] == model].iloc[0]['zstore'],chunks={})\n",
      "/var/folders/ys/qmftlyyx3dj63021dv4205g80000gn/T/ipykernel_85352/2736516945.py:23: SerializationWarning: Unable to decode time axis into full numpy.datetime64[ns] objects, continuing using cftime.datetime objects instead, reason: dates out of range. To silence this warning use a coarser resolution 'time_unit' or specify 'use_cftime=True'.\n",
      "  piC_ds = xr.open_zarr(piC_tas_df[piC_tas_df['source_id'] == model].iloc[0]['zstore'],chunks={})\n",
      "/var/folders/ys/qmftlyyx3dj63021dv4205g80000gn/T/ipykernel_85352/2736516945.py:23: SerializationWarning: Unable to decode time axis into full numpy.datetime64[ns] objects, continuing using cftime.datetime objects instead, reason: dates out of range. To silence this warning use a coarser resolution 'time_unit' or specify 'use_cftime=True'.\n",
      "  piC_ds = xr.open_zarr(piC_tas_df[piC_tas_df['source_id'] == model].iloc[0]['zstore'],chunks={})\n",
      "/var/folders/ys/qmftlyyx3dj63021dv4205g80000gn/T/ipykernel_85352/2736516945.py:23: SerializationWarning: Unable to decode time axis into full numpy.datetime64[ns] objects, continuing using cftime.datetime objects instead, reason: dates out of range. To silence this warning use a coarser resolution 'time_unit' or specify 'use_cftime=True'.\n",
      "  piC_ds = xr.open_zarr(piC_tas_df[piC_tas_df['source_id'] == model].iloc[0]['zstore'],chunks={})\n",
      "/var/folders/ys/qmftlyyx3dj63021dv4205g80000gn/T/ipykernel_85352/2736516945.py:23: SerializationWarning: Unable to decode time axis into full numpy.datetime64[ns] objects, continuing using cftime.datetime objects instead, reason: dates out of range. To silence this warning use a coarser resolution 'time_unit' or specify 'use_cftime=True'.\n",
      "  piC_ds = xr.open_zarr(piC_tas_df[piC_tas_df['source_id'] == model].iloc[0]['zstore'],chunks={})\n",
      "/var/folders/ys/qmftlyyx3dj63021dv4205g80000gn/T/ipykernel_85352/2736516945.py:23: SerializationWarning: Unable to decode time axis into full numpy.datetime64[ns] objects, continuing using cftime.datetime objects instead, reason: dates out of range. To silence this warning use a coarser resolution 'time_unit' or specify 'use_cftime=True'.\n",
      "  piC_ds = xr.open_zarr(piC_tas_df[piC_tas_df['source_id'] == model].iloc[0]['zstore'],chunks={})\n",
      "/var/folders/ys/qmftlyyx3dj63021dv4205g80000gn/T/ipykernel_85352/2736516945.py:23: SerializationWarning: Unable to decode time axis into full numpy.datetime64 objects, continuing using cftime.datetime objects instead, reason: dates prior reform date (1582-10-15). To silence this warning specify 'use_cftime=True'.\n",
      "  piC_ds = xr.open_zarr(piC_tas_df[piC_tas_df['source_id'] == model].iloc[0]['zstore'],chunks={})\n",
      "/var/folders/ys/qmftlyyx3dj63021dv4205g80000gn/T/ipykernel_85352/2736516945.py:41: SerializationWarning: Unable to decode time axis into full numpy.datetime64[ns] objects, continuing using cftime.datetime objects instead, reason: dates out of range. To silence this warning use a coarser resolution 'time_unit' or specify 'use_cftime=True'.\n",
      "  ds = xr.open_dataset(file)\n",
      "/var/folders/ys/qmftlyyx3dj63021dv4205g80000gn/T/ipykernel_85352/2736516945.py:41: SerializationWarning: Unable to decode time axis into full numpy.datetime64[ns] objects, continuing using cftime.datetime objects instead, reason: dates out of range. To silence this warning use a coarser resolution 'time_unit' or specify 'use_cftime=True'.\n",
      "  ds = xr.open_dataset(file)\n",
      "/var/folders/ys/qmftlyyx3dj63021dv4205g80000gn/T/ipykernel_85352/2736516945.py:41: SerializationWarning: Unable to decode time axis into full numpy.datetime64[ns] objects, continuing using cftime.datetime objects instead, reason: dates out of range. To silence this warning use a coarser resolution 'time_unit' or specify 'use_cftime=True'.\n",
      "  ds = xr.open_dataset(file)\n",
      "/var/folders/ys/qmftlyyx3dj63021dv4205g80000gn/T/ipykernel_85352/2736516945.py:41: SerializationWarning: Unable to decode time axis into full numpy.datetime64[ns] objects, continuing using cftime.datetime objects instead, reason: dates out of range. To silence this warning use a coarser resolution 'time_unit' or specify 'use_cftime=True'.\n",
      "  ds = xr.open_dataset(file)\n",
      "/var/folders/ys/qmftlyyx3dj63021dv4205g80000gn/T/ipykernel_85352/2736516945.py:41: SerializationWarning: Unable to decode time axis into full numpy.datetime64[ns] objects, continuing using cftime.datetime objects instead, reason: dates out of range. To silence this warning use a coarser resolution 'time_unit' or specify 'use_cftime=True'.\n",
      "  ds = xr.open_dataset(file)\n",
      "/var/folders/ys/qmftlyyx3dj63021dv4205g80000gn/T/ipykernel_85352/2736516945.py:41: SerializationWarning: Unable to decode time axis into full numpy.datetime64[ns] objects, continuing using cftime.datetime objects instead, reason: dates out of range. To silence this warning use a coarser resolution 'time_unit' or specify 'use_cftime=True'.\n",
      "  ds = xr.open_dataset(file)\n",
      "/var/folders/ys/qmftlyyx3dj63021dv4205g80000gn/T/ipykernel_85352/2736516945.py:41: SerializationWarning: Unable to decode time axis into full numpy.datetime64[ns] objects, continuing using cftime.datetime objects instead, reason: dates out of range. To silence this warning use a coarser resolution 'time_unit' or specify 'use_cftime=True'.\n",
      "  ds = xr.open_dataset(file)\n",
      "/var/folders/ys/qmftlyyx3dj63021dv4205g80000gn/T/ipykernel_85352/2736516945.py:41: SerializationWarning: Unable to decode time axis into full numpy.datetime64[ns] objects, continuing using cftime.datetime objects instead, reason: dates out of range. To silence this warning use a coarser resolution 'time_unit' or specify 'use_cftime=True'.\n",
      "  ds = xr.open_dataset(file)\n",
      "/var/folders/ys/qmftlyyx3dj63021dv4205g80000gn/T/ipykernel_85352/2736516945.py:41: SerializationWarning: Unable to decode time axis into full numpy.datetime64[ns] objects, continuing using cftime.datetime objects instead, reason: dates out of range. To silence this warning use a coarser resolution 'time_unit' or specify 'use_cftime=True'.\n",
      "  ds = xr.open_dataset(file)\n",
      "/var/folders/ys/qmftlyyx3dj63021dv4205g80000gn/T/ipykernel_85352/2736516945.py:41: SerializationWarning: Unable to decode time axis into full numpy.datetime64[ns] objects, continuing using cftime.datetime objects instead, reason: dates out of range. To silence this warning use a coarser resolution 'time_unit' or specify 'use_cftime=True'.\n",
      "  ds = xr.open_dataset(file)\n",
      "/var/folders/ys/qmftlyyx3dj63021dv4205g80000gn/T/ipykernel_85352/2736516945.py:41: SerializationWarning: Unable to decode time axis into full numpy.datetime64[ns] objects, continuing using cftime.datetime objects instead, reason: dates out of range. To silence this warning use a coarser resolution 'time_unit' or specify 'use_cftime=True'.\n",
      "  ds = xr.open_dataset(file)\n",
      "/var/folders/ys/qmftlyyx3dj63021dv4205g80000gn/T/ipykernel_85352/2736516945.py:42: SerializationWarning: Unable to decode time axis into full numpy.datetime64[ns] objects, continuing using cftime.datetime objects instead, reason: dates out of range. To silence this warning use a coarser resolution 'time_unit' or specify 'use_cftime=True'.\n",
      "  ds_pi = xr.open_dataset(pi_file[0])\n",
      "/var/folders/ys/qmftlyyx3dj63021dv4205g80000gn/T/ipykernel_85352/2736516945.py:41: SerializationWarning: Unable to decode time axis into full numpy.datetime64[ns] objects, continuing using cftime.datetime objects instead, reason: dates out of range. To silence this warning use a coarser resolution 'time_unit' or specify 'use_cftime=True'.\n",
      "  ds = xr.open_dataset(file)\n",
      "/var/folders/ys/qmftlyyx3dj63021dv4205g80000gn/T/ipykernel_85352/2736516945.py:41: SerializationWarning: Unable to decode time axis into full numpy.datetime64[ns] objects, continuing using cftime.datetime objects instead, reason: dates out of range. To silence this warning use a coarser resolution 'time_unit' or specify 'use_cftime=True'.\n",
      "  ds = xr.open_dataset(file)\n",
      "/var/folders/ys/qmftlyyx3dj63021dv4205g80000gn/T/ipykernel_85352/2736516945.py:41: SerializationWarning: Unable to decode time axis into full numpy.datetime64[ns] objects, continuing using cftime.datetime objects instead, reason: dates out of range. To silence this warning use a coarser resolution 'time_unit' or specify 'use_cftime=True'.\n",
      "  ds = xr.open_dataset(file)\n",
      "/var/folders/ys/qmftlyyx3dj63021dv4205g80000gn/T/ipykernel_85352/2736516945.py:41: SerializationWarning: Unable to decode time axis into full numpy.datetime64[ns] objects, continuing using cftime.datetime objects instead, reason: dates out of range. To silence this warning use a coarser resolution 'time_unit' or specify 'use_cftime=True'.\n",
      "  ds = xr.open_dataset(file)\n",
      "/var/folders/ys/qmftlyyx3dj63021dv4205g80000gn/T/ipykernel_85352/2736516945.py:41: SerializationWarning: Unable to decode time axis into full numpy.datetime64[ns] objects, continuing using cftime.datetime objects instead, reason: dates out of range. To silence this warning use a coarser resolution 'time_unit' or specify 'use_cftime=True'.\n",
      "  ds = xr.open_dataset(file)\n",
      "/var/folders/ys/qmftlyyx3dj63021dv4205g80000gn/T/ipykernel_85352/2736516945.py:41: SerializationWarning: Unable to decode time axis into full numpy.datetime64[ns] objects, continuing using cftime.datetime objects instead, reason: dates out of range. To silence this warning use a coarser resolution 'time_unit' or specify 'use_cftime=True'.\n",
      "  ds = xr.open_dataset(file)\n",
      "/var/folders/ys/qmftlyyx3dj63021dv4205g80000gn/T/ipykernel_85352/2736516945.py:41: SerializationWarning: Unable to decode time axis into full numpy.datetime64[ns] objects, continuing using cftime.datetime objects instead, reason: dates out of range. To silence this warning use a coarser resolution 'time_unit' or specify 'use_cftime=True'.\n",
      "  ds = xr.open_dataset(file)\n",
      "/var/folders/ys/qmftlyyx3dj63021dv4205g80000gn/T/ipykernel_85352/2736516945.py:41: SerializationWarning: Unable to decode time axis into full numpy.datetime64[ns] objects, continuing using cftime.datetime objects instead, reason: dates out of range. To silence this warning use a coarser resolution 'time_unit' or specify 'use_cftime=True'.\n",
      "  ds = xr.open_dataset(file)\n",
      "/var/folders/ys/qmftlyyx3dj63021dv4205g80000gn/T/ipykernel_85352/2736516945.py:41: SerializationWarning: Unable to decode time axis into full numpy.datetime64[ns] objects, continuing using cftime.datetime objects instead, reason: dates out of range. To silence this warning use a coarser resolution 'time_unit' or specify 'use_cftime=True'.\n",
      "  ds = xr.open_dataset(file)\n"
     ]
    }
   ],
   "source": [
    "### MONTHLY AVERAGES FOR EVERY MODEL AND TIME PERIOD ####\n",
    "regions = {\n",
    "    'global':[-90,90],\n",
    "    'northern_hemisphere':[0,90],\n",
    "    'tropics':[-30,30],\n",
    "    'southern_hemisphere':[-90,0],\n",
    "}\n",
    "\n",
    "monthly_files = glob.glob(f'{root_path}/*/*_tas_monthly.nc')\n",
    "_results = []\n",
    "\n",
    "for region, bnds in regions.items():\n",
    "    for file in monthly_files:\n",
    "        model = file.split('/')[8]\n",
    "        period = file.split('/')[9].split('_')[0]\n",
    "\n",
    "        ds = xr.open_dataset(file)\n",
    "    \n",
    "        ds_slice = ds.sel(lat = slice(bnds[0],bnds[1]))\n",
    "        ds_zmean = ds_slice['tas'].weighted(ds_slice['weight'].fillna(0)).mean(dim=['lat','lon'])\n",
    "\n",
    "        # get pi control to calculate anomaly\n",
    "        piC_ds = xr.open_zarr(piC_tas_df[piC_tas_df['source_id'] == model].iloc[0]['zstore'],chunks={})\n",
    "        piC_zmean = piC_ds.sel(lat = slice(bnds[0],bnds[1]))['tas'].weighted(ds_slice['weight'].fillna(0)).mean(dim=['lat','lon'])\n",
    "        piC_zmean = piC_zmean.groupby('time.month').mean()\n",
    "        \n",
    "        df_zmean = ds_zmean.to_dataframe().reset_index()\n",
    "        df_zmean = df_zmean.merge(piC_zmean.to_dataframe().reset_index()[['month','tas']].rename(columns={'tas':'tas_pi'}),on='month')\n",
    "\n",
    "        df_zmean['model'] = model\n",
    "        df_zmean['period'] = period\n",
    "        df_zmean['region'] = region\n",
    "        df_zmean['co2_exp'] = np.nan\n",
    "        _results.append(df_zmean)\n",
    "\n",
    "    for file in eocene_models:\n",
    "        model = file.split('/')[17]\n",
    "        co2 = file.split('/')[18].split('-')[-1]\n",
    "        pi_file = [x for x in piC_eocene if model in x]\n",
    "\n",
    "        ds = xr.open_dataset(file)\n",
    "        ds_pi = xr.open_dataset(pi_file[0])\n",
    "        \n",
    "        if \"t\" in ds.dims:\n",
    "            ds = ds.rename({'t':'time','latitude':'lat','longitude':'lon'})\n",
    "            ds_pi = ds_pi.rename({'t':'time','latitude':'lat','longitude':'lon'})\n",
    "        if \"time_counter\" in ds.dims:\n",
    "            ds = ds.rename({'time_counter':'time'})\n",
    "            ds_pi = ds_pi.rename({'time_counter':'time'})\n",
    "\n",
    "        ds = ds.sortby('lat')\n",
    "        ds_pi = ds_pi.sortby('lat')\n",
    "        \n",
    "        ds = ds.groupby('time.month').mean()\n",
    "        ds_pi = ds_pi.groupby('time.month').mean()\n",
    "\n",
    "        ds_slice = ds.sel(lat = slice(bnds[0],bnds[1]))\n",
    "        ds_pi_slice = ds_pi.sel(lat = slice(bnds[0],bnds[1]))\n",
    "\n",
    "        weights = np.cos(np.deg2rad(ds_slice.lat))\n",
    "        weights = weights.expand_dims({\"lon\": ds_slice.lon})\n",
    "\n",
    "        ds_zmean = ds_slice['tas'].weighted(weights.fillna(0)).mean(dim=['lat','lon'])\n",
    "        ds_pi_zmean = ds_pi_slice['tas'].weighted(weights.fillna(0)).mean(dim=['lat','lon'])\n",
    "\n",
    "        df_zmean = ds_zmean.to_dataframe().reset_index()\n",
    "        df_zmean = df_zmean.merge(ds_pi_zmean.to_dataframe().reset_index()[['month','tas']].rename(columns={'tas':'tas_pi'}),on='month')\n",
    "\n",
    "        df_zmean['model'] = model\n",
    "        df_zmean['period'] = 'eocene'\n",
    "        df_zmean['region'] = region\n",
    "        df_zmean['co2_exp'] = co2\n",
    "        _results.append(df_zmean)\n",
    "\n",
    "seasonal_paleo_results = pd.concat(_results)\n",
    "# seasonal_paleo_results[(seasonal_paleo_results['period'] == 'lig127k') & (seasonal_paleo_results['region'] == 'global')].pivot_table(index='month',columns='model',values = 'tas').plot()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 53,
   "id": "b39a0f97",
   "metadata": {},
   "outputs": [],
   "source": [
    "seasonal_paleo_results['tas_anom'] = seasonal_paleo_results['tas'] - seasonal_paleo_results['tas_pi']\n",
    "seasonal_obs = pd.read_csv('observational_data/paleo/processed/monthly_mean_zonal_obs.csv').drop(columns=['Unnamed: 0'])\n",
    "seasonal_obs['period'] = 'lgm'\n",
    "seasonal_obs = seasonal_obs[['month','period','region','mean temperature [degreesC]']].rename(columns={'mean temperature [degreesC]':'tas_obs'})\n",
    "monthly_zonal_means = seasonal_paleo_results.merge(seasonal_obs,on=['month','period','region'],how='outer')\n",
    "monthly_zonal_means['mae'] = (monthly_zonal_means['tas_anom'] - monthly_zonal_means['tas_obs']).abs()\n",
    "monthly_zonal_means.drop(columns=['height']).to_csv('results/paleo/monthly_zonal_means.csv')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "id": "44c681aa",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "WARNING:google.auth._default:No project ID could be determined. Consider running `gcloud config set project` or setting the GOOGLE_CLOUD_PROJECT environment variable\n",
      "/var/folders/ys/qmftlyyx3dj63021dv4205g80000gn/T/ipykernel_85352/2753333000.py:16: SerializationWarning: Unable to decode time axis into full numpy.datetime64[ns] objects, continuing using cftime.datetime objects instead, reason: dates out of range. To silence this warning use a coarser resolution 'time_unit' or specify 'use_cftime=True'.\n",
      "  piC_ds = xr.open_zarr(piC_tas_df[piC_tas_df['source_id'] == model].iloc[0]['zstore'],chunks={})\n",
      "/var/folders/ys/qmftlyyx3dj63021dv4205g80000gn/T/ipykernel_85352/2753333000.py:16: SerializationWarning: Unable to decode time axis into full numpy.datetime64[ns] objects, continuing using cftime.datetime objects instead, reason: dates out of range. To silence this warning use a coarser resolution 'time_unit' or specify 'use_cftime=True'.\n",
      "  piC_ds = xr.open_zarr(piC_tas_df[piC_tas_df['source_id'] == model].iloc[0]['zstore'],chunks={})\n",
      "/var/folders/ys/qmftlyyx3dj63021dv4205g80000gn/T/ipykernel_85352/2753333000.py:16: SerializationWarning: Unable to decode time axis into full numpy.datetime64 objects, continuing using cftime.datetime objects instead, reason: dates prior reform date (1582-10-15). To silence this warning specify 'use_cftime=True'.\n",
      "  piC_ds = xr.open_zarr(piC_tas_df[piC_tas_df['source_id'] == model].iloc[0]['zstore'],chunks={})\n",
      "/var/folders/ys/qmftlyyx3dj63021dv4205g80000gn/T/ipykernel_85352/2753333000.py:16: SerializationWarning: Unable to decode time axis into full numpy.datetime64 objects, continuing using cftime.datetime objects instead, reason: dates prior reform date (1582-10-15). To silence this warning specify 'use_cftime=True'.\n",
      "  piC_ds = xr.open_zarr(piC_tas_df[piC_tas_df['source_id'] == model].iloc[0]['zstore'],chunks={})\n",
      "/var/folders/ys/qmftlyyx3dj63021dv4205g80000gn/T/ipykernel_85352/2753333000.py:16: SerializationWarning: Unable to decode time axis into full numpy.datetime64[ns] objects, continuing using cftime.datetime objects instead, reason: dates out of range. To silence this warning use a coarser resolution 'time_unit' or specify 'use_cftime=True'.\n",
      "  piC_ds = xr.open_zarr(piC_tas_df[piC_tas_df['source_id'] == model].iloc[0]['zstore'],chunks={})\n",
      "/var/folders/ys/qmftlyyx3dj63021dv4205g80000gn/T/ipykernel_85352/2753333000.py:16: SerializationWarning: Unable to decode time axis into full numpy.datetime64[ns] objects, continuing using cftime.datetime objects instead, reason: dates out of range. To silence this warning use a coarser resolution 'time_unit' or specify 'use_cftime=True'.\n",
      "  piC_ds = xr.open_zarr(piC_tas_df[piC_tas_df['source_id'] == model].iloc[0]['zstore'],chunks={})\n",
      "/var/folders/ys/qmftlyyx3dj63021dv4205g80000gn/T/ipykernel_85352/2753333000.py:16: SerializationWarning: Unable to decode time axis into full numpy.datetime64[ns] objects, continuing using cftime.datetime objects instead, reason: dates out of range. To silence this warning use a coarser resolution 'time_unit' or specify 'use_cftime=True'.\n",
      "  piC_ds = xr.open_zarr(piC_tas_df[piC_tas_df['source_id'] == model].iloc[0]['zstore'],chunks={})\n",
      "/var/folders/ys/qmftlyyx3dj63021dv4205g80000gn/T/ipykernel_85352/2753333000.py:16: SerializationWarning: Unable to decode time axis into full numpy.datetime64[ns] objects, continuing using cftime.datetime objects instead, reason: dates out of range. To silence this warning use a coarser resolution 'time_unit' or specify 'use_cftime=True'.\n",
      "  piC_ds = xr.open_zarr(piC_tas_df[piC_tas_df['source_id'] == model].iloc[0]['zstore'],chunks={})\n",
      "/var/folders/ys/qmftlyyx3dj63021dv4205g80000gn/T/ipykernel_85352/2753333000.py:16: SerializationWarning: Unable to decode time axis into full numpy.datetime64[ns] objects, continuing using cftime.datetime objects instead, reason: dates out of range. To silence this warning use a coarser resolution 'time_unit' or specify 'use_cftime=True'.\n",
      "  piC_ds = xr.open_zarr(piC_tas_df[piC_tas_df['source_id'] == model].iloc[0]['zstore'],chunks={})\n",
      "/var/folders/ys/qmftlyyx3dj63021dv4205g80000gn/T/ipykernel_85352/2753333000.py:16: SerializationWarning: Unable to decode time axis into full numpy.datetime64[ns] objects, continuing using cftime.datetime objects instead, reason: dates out of range. To silence this warning use a coarser resolution 'time_unit' or specify 'use_cftime=True'.\n",
      "  piC_ds = xr.open_zarr(piC_tas_df[piC_tas_df['source_id'] == model].iloc[0]['zstore'],chunks={})\n",
      "/var/folders/ys/qmftlyyx3dj63021dv4205g80000gn/T/ipykernel_85352/2753333000.py:16: SerializationWarning: Unable to decode time axis into full numpy.datetime64[ns] objects, continuing using cftime.datetime objects instead, reason: dates out of range. To silence this warning use a coarser resolution 'time_unit' or specify 'use_cftime=True'.\n",
      "  piC_ds = xr.open_zarr(piC_tas_df[piC_tas_df['source_id'] == model].iloc[0]['zstore'],chunks={})\n",
      "/var/folders/ys/qmftlyyx3dj63021dv4205g80000gn/T/ipykernel_85352/2753333000.py:16: SerializationWarning: Unable to decode time axis into full numpy.datetime64[ns] objects, continuing using cftime.datetime objects instead, reason: dates out of range. To silence this warning use a coarser resolution 'time_unit' or specify 'use_cftime=True'.\n",
      "  piC_ds = xr.open_zarr(piC_tas_df[piC_tas_df['source_id'] == model].iloc[0]['zstore'],chunks={})\n",
      "/var/folders/ys/qmftlyyx3dj63021dv4205g80000gn/T/ipykernel_85352/2753333000.py:16: SerializationWarning: Unable to decode time axis into full numpy.datetime64[ns] objects, continuing using cftime.datetime objects instead, reason: dates out of range. To silence this warning use a coarser resolution 'time_unit' or specify 'use_cftime=True'.\n",
      "  piC_ds = xr.open_zarr(piC_tas_df[piC_tas_df['source_id'] == model].iloc[0]['zstore'],chunks={})\n",
      "/var/folders/ys/qmftlyyx3dj63021dv4205g80000gn/T/ipykernel_85352/2753333000.py:16: SerializationWarning: Unable to decode time axis into full numpy.datetime64[ns] objects, continuing using cftime.datetime objects instead, reason: dates out of range. To silence this warning use a coarser resolution 'time_unit' or specify 'use_cftime=True'.\n",
      "  piC_ds = xr.open_zarr(piC_tas_df[piC_tas_df['source_id'] == model].iloc[0]['zstore'],chunks={})\n",
      "/var/folders/ys/qmftlyyx3dj63021dv4205g80000gn/T/ipykernel_85352/2753333000.py:16: SerializationWarning: Unable to decode time axis into full numpy.datetime64[ns] objects, continuing using cftime.datetime objects instead, reason: dates out of range. To silence this warning use a coarser resolution 'time_unit' or specify 'use_cftime=True'.\n",
      "  piC_ds = xr.open_zarr(piC_tas_df[piC_tas_df['source_id'] == model].iloc[0]['zstore'],chunks={})\n",
      "/var/folders/ys/qmftlyyx3dj63021dv4205g80000gn/T/ipykernel_85352/2753333000.py:16: SerializationWarning: Unable to decode time axis into full numpy.datetime64[ns] objects, continuing using cftime.datetime objects instead, reason: dates out of range. To silence this warning use a coarser resolution 'time_unit' or specify 'use_cftime=True'.\n",
      "  piC_ds = xr.open_zarr(piC_tas_df[piC_tas_df['source_id'] == model].iloc[0]['zstore'],chunks={})\n",
      "/var/folders/ys/qmftlyyx3dj63021dv4205g80000gn/T/ipykernel_85352/2753333000.py:16: SerializationWarning: Unable to decode time axis into full numpy.datetime64[ns] objects, continuing using cftime.datetime objects instead, reason: dates out of range. To silence this warning use a coarser resolution 'time_unit' or specify 'use_cftime=True'.\n",
      "  piC_ds = xr.open_zarr(piC_tas_df[piC_tas_df['source_id'] == model].iloc[0]['zstore'],chunks={})\n",
      "/var/folders/ys/qmftlyyx3dj63021dv4205g80000gn/T/ipykernel_85352/2753333000.py:16: SerializationWarning: Unable to decode time axis into full numpy.datetime64[ns] objects, continuing using cftime.datetime objects instead, reason: dates out of range. To silence this warning use a coarser resolution 'time_unit' or specify 'use_cftime=True'.\n",
      "  piC_ds = xr.open_zarr(piC_tas_df[piC_tas_df['source_id'] == model].iloc[0]['zstore'],chunks={})\n",
      "/var/folders/ys/qmftlyyx3dj63021dv4205g80000gn/T/ipykernel_85352/2753333000.py:16: SerializationWarning: Unable to decode time axis into full numpy.datetime64[ns] objects, continuing using cftime.datetime objects instead, reason: dates out of range. To silence this warning use a coarser resolution 'time_unit' or specify 'use_cftime=True'.\n",
      "  piC_ds = xr.open_zarr(piC_tas_df[piC_tas_df['source_id'] == model].iloc[0]['zstore'],chunks={})\n",
      "/var/folders/ys/qmftlyyx3dj63021dv4205g80000gn/T/ipykernel_85352/2753333000.py:16: SerializationWarning: Unable to decode time axis into full numpy.datetime64[ns] objects, continuing using cftime.datetime objects instead, reason: dates out of range. To silence this warning use a coarser resolution 'time_unit' or specify 'use_cftime=True'.\n",
      "  piC_ds = xr.open_zarr(piC_tas_df[piC_tas_df['source_id'] == model].iloc[0]['zstore'],chunks={})\n",
      "/var/folders/ys/qmftlyyx3dj63021dv4205g80000gn/T/ipykernel_85352/2753333000.py:16: SerializationWarning: Unable to decode time axis into full numpy.datetime64[ns] objects, continuing using cftime.datetime objects instead, reason: dates out of range. To silence this warning use a coarser resolution 'time_unit' or specify 'use_cftime=True'.\n",
      "  piC_ds = xr.open_zarr(piC_tas_df[piC_tas_df['source_id'] == model].iloc[0]['zstore'],chunks={})\n",
      "/var/folders/ys/qmftlyyx3dj63021dv4205g80000gn/T/ipykernel_85352/2753333000.py:16: SerializationWarning: Unable to decode time axis into full numpy.datetime64[ns] objects, continuing using cftime.datetime objects instead, reason: dates out of range. To silence this warning use a coarser resolution 'time_unit' or specify 'use_cftime=True'.\n",
      "  piC_ds = xr.open_zarr(piC_tas_df[piC_tas_df['source_id'] == model].iloc[0]['zstore'],chunks={})\n",
      "/var/folders/ys/qmftlyyx3dj63021dv4205g80000gn/T/ipykernel_85352/2753333000.py:16: SerializationWarning: Unable to decode time axis into full numpy.datetime64[ns] objects, continuing using cftime.datetime objects instead, reason: dates out of range. To silence this warning use a coarser resolution 'time_unit' or specify 'use_cftime=True'.\n",
      "  piC_ds = xr.open_zarr(piC_tas_df[piC_tas_df['source_id'] == model].iloc[0]['zstore'],chunks={})\n",
      "/var/folders/ys/qmftlyyx3dj63021dv4205g80000gn/T/ipykernel_85352/2753333000.py:16: SerializationWarning: Unable to decode time axis into full numpy.datetime64[ns] objects, continuing using cftime.datetime objects instead, reason: dates out of range. To silence this warning use a coarser resolution 'time_unit' or specify 'use_cftime=True'.\n",
      "  piC_ds = xr.open_zarr(piC_tas_df[piC_tas_df['source_id'] == model].iloc[0]['zstore'],chunks={})\n",
      "/var/folders/ys/qmftlyyx3dj63021dv4205g80000gn/T/ipykernel_85352/2753333000.py:16: SerializationWarning: Unable to decode time axis into full numpy.datetime64[ns] objects, continuing using cftime.datetime objects instead, reason: dates out of range. To silence this warning use a coarser resolution 'time_unit' or specify 'use_cftime=True'.\n",
      "  piC_ds = xr.open_zarr(piC_tas_df[piC_tas_df['source_id'] == model].iloc[0]['zstore'],chunks={})\n",
      "/var/folders/ys/qmftlyyx3dj63021dv4205g80000gn/T/ipykernel_85352/2753333000.py:16: SerializationWarning: Unable to decode time axis into full numpy.datetime64[ns] objects, continuing using cftime.datetime objects instead, reason: dates out of range. To silence this warning use a coarser resolution 'time_unit' or specify 'use_cftime=True'.\n",
      "  piC_ds = xr.open_zarr(piC_tas_df[piC_tas_df['source_id'] == model].iloc[0]['zstore'],chunks={})\n",
      "/var/folders/ys/qmftlyyx3dj63021dv4205g80000gn/T/ipykernel_85352/2753333000.py:16: SerializationWarning: Unable to decode time axis into full numpy.datetime64[ns] objects, continuing using cftime.datetime objects instead, reason: dates out of range. To silence this warning use a coarser resolution 'time_unit' or specify 'use_cftime=True'.\n",
      "  piC_ds = xr.open_zarr(piC_tas_df[piC_tas_df['source_id'] == model].iloc[0]['zstore'],chunks={})\n",
      "/var/folders/ys/qmftlyyx3dj63021dv4205g80000gn/T/ipykernel_85352/2753333000.py:16: SerializationWarning: Unable to decode time axis into full numpy.datetime64[ns] objects, continuing using cftime.datetime objects instead, reason: dates out of range. To silence this warning use a coarser resolution 'time_unit' or specify 'use_cftime=True'.\n",
      "  piC_ds = xr.open_zarr(piC_tas_df[piC_tas_df['source_id'] == model].iloc[0]['zstore'],chunks={})\n",
      "/var/folders/ys/qmftlyyx3dj63021dv4205g80000gn/T/ipykernel_85352/2753333000.py:16: SerializationWarning: Unable to decode time axis into full numpy.datetime64[ns] objects, continuing using cftime.datetime objects instead, reason: dates out of range. To silence this warning use a coarser resolution 'time_unit' or specify 'use_cftime=True'.\n",
      "  piC_ds = xr.open_zarr(piC_tas_df[piC_tas_df['source_id'] == model].iloc[0]['zstore'],chunks={})\n",
      "/var/folders/ys/qmftlyyx3dj63021dv4205g80000gn/T/ipykernel_85352/2753333000.py:16: SerializationWarning: Unable to decode time axis into full numpy.datetime64 objects, continuing using cftime.datetime objects instead, reason: dates prior reform date (1582-10-15). To silence this warning specify 'use_cftime=True'.\n",
      "  piC_ds = xr.open_zarr(piC_tas_df[piC_tas_df['source_id'] == model].iloc[0]['zstore'],chunks={})\n"
     ]
    }
   ],
   "source": [
    "### ANNUAL AVERAGES FOR EVERY MODEL AND TIME PERIOD ####\n",
    "\n",
    "df = pd.read_csv(\"https://cmip6.storage.googleapis.com/pangeo-cmip6.csv\")\n",
    "piC_tas_df = df[(df['activity_id'] == 'CMIP') & (df['experiment_id'] == 'piControl')& (df['table_id'] == 'Amon')& (df['variable_id'] == 'tas')]#['table_id'].unique()\n",
    "\n",
    "annual_files = glob.glob(f'{root_path}/*/*_tas_annual.nc')\n",
    "_results = []\n",
    "\n",
    "for file in annual_files:\n",
    "    model = file.split('/')[8]\n",
    "    period = file.split('/')[9].split('_')[0]\n",
    "\n",
    "    ds = xr.open_dataset(file)\n",
    "\n",
    "    # get pi control to calculate anomaly\n",
    "    piC_ds = xr.open_zarr(piC_tas_df[piC_tas_df['source_id'] == model].iloc[0]['zstore'],chunks={})\n",
    "    ds_anom = ds - piC_ds.mean(dim='time').drop_vars(['height','lat_bnds','lon_bnds','time_bnds'],errors='ignore')\n",
    "\n",
    "    ds_zmean = ds_anom['tas'].weighted(ds['weight'].fillna(0)).mean(dim=['lat','lon'])\n",
    "\n",
    "    df_zmean = pd.DataFrame({\n",
    "        'tas':[ds_zmean.values.tolist()],\n",
    "        'model':[model],\n",
    "        'period':[period],\n",
    "        'region':['global'],\n",
    "    })\n",
    "    _results.append(df_zmean)\n",
    "\n",
    "annual_paleo_results = pd.concat(_results)\n",
    "\n",
    "annual_paleo_results['Time Period idx'] = 1\n",
    "annual_paleo_results.loc[annual_paleo_results['period'] == 'lig127k','Time Period idx'] = 2\n",
    "annual_paleo_results.loc[annual_paleo_results['period'] == 'lgm','Time Period idx'] = 3\n",
    "annual_paleo_results.loc[annual_paleo_results['period'] == 'midHolocene','Time Period idx'] = 4\n",
    "\n",
    "\n",
    "# get eocene annual results\n",
    "eeco_files = glob.glob('/Users/willatobin/Documents/SIO/ClimateBench2/backend/paleo_data_cache/deepmip/dap.ceda.ac.uk/badc/cmip6/data/CMIP6Plus/DeepMIP/deepmip-eocene-p1/*/*/*/*/*/*')\n",
    "\n",
    "eeco_models_df = pd.concat([\n",
    "    pd.DataFrame(eeco_files).rename(columns={0:'local_path'}),\n",
    "    pd.DataFrame(eeco_files)[0].str.split('/',expand=True)[[17,18]].rename(columns={17:'model',18:'experiment'})\n",
    "],axis=1)\n",
    "\n",
    "eeco_models_df['experiment_id'] = eeco_models_df['experiment'].str[-1]\n",
    "eeco_models_df.loc[eeco_models_df['experiment_id'] == 'I','experiment_id'] = 0\n",
    "eeco_models_df['experiment_id'] = eeco_models_df['experiment_id'].astype(int)\n",
    "\n",
    "eeco_exp_models = eeco_models_df[~(eeco_models_df['experiment_id'] == 0)]  \n",
    "\n",
    "_results = []\n",
    "for row in eeco_exp_models.itertuples(index=False):\n",
    "    model = row.model\n",
    "    eeco_path = row.local_path\n",
    "    pi_path = eeco_models_df[(eeco_models_df['model'] == model) & (eeco_models_df['experiment_id'] == 0)].iloc[0]['local_path']\n",
    "\n",
    "    ds_piC = xr.open_dataset(pi_path,chunks={},decode_times=False)\n",
    "    ds_eeco = xr.open_dataset(eeco_path,chunks={},decode_times=False)\n",
    "\n",
    "\n",
    "    if \"t\" in ds_piC.dims:\n",
    "        ds_piC = ds_piC.rename({'t':'time','latitude':'lat','longitude':'lon'})\n",
    "        ds_eeco = ds_eeco.rename({'t':'time','latitude':'lat','longitude':'lon'})\n",
    "    if \"time_counter\" in ds_piC.dims:\n",
    "        ds_piC = ds_piC.rename({'time_counter':'time'})\n",
    "        ds_eeco = ds_eeco.rename({'time_counter':'time'})\n",
    "\n",
    "    ds_piC = ds_piC.mean(dim='time').drop_vars(['height','lat_bnds','lon_bnds'],errors='ignore')\n",
    "    ds_eeco = ds_eeco.mean(dim='time').drop_vars(['height','lat_bnds','lon_bnds'],errors='ignore')\n",
    "\n",
    "    ds_anom = ds_eeco - ds_piC\n",
    "\n",
    "    weights = np.cos(np.deg2rad(ds_anom.lat))\n",
    "    weights = weights.expand_dims({\"lon\": ds_anom.lon})\n",
    "    weights.name = 'areacella'\n",
    "\n",
    "    zmean = ds_anom.weighted(weights.fillna(0)).mean().compute()\n",
    "\n",
    "    df_zmean = pd.DataFrame({\n",
    "        'tas':[zmean['tas'].values.tolist()],\n",
    "        'model':[model],\n",
    "        'period':['eocene'],\n",
    "        'region':['global'],\n",
    "        'co2_exp':[row.experiment_id],\n",
    "    })\n",
    "    _results.append(df_zmean)\n",
    "annual_eocene_results = pd.concat(_results)\n",
    "annual_eocene_results['Time Period idx'] = 0\n",
    "\n",
    "annual_paleo_results = pd.concat([\n",
    "    annual_eocene_results,\n",
    "    annual_paleo_results\n",
    "])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "a636d523",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "<matplotlib.legend.Legend at 0x31f36d400>"
      ]
     },
     "execution_count": 9,
     "metadata": {},
     "output_type": "execute_result"
    },
    {
     "data": {
      "image/png": "iVBORw0KGgoAAAANSUhEUgAAAiIAAAHZCAYAAAC7CVBtAAAAOnRFWHRTb2Z0d2FyZQBNYXRwbG90bGliIHZlcnNpb24zLjEwLjMsIGh0dHBzOi8vbWF0cGxvdGxpYi5vcmcvZiW1igAAAAlwSFlzAAAPYQAAD2EBqD+naQAAU4xJREFUeJzt3Xd8zdf/B/DXvSHjkoQQSUSWLVbFDE3tHbSp0SqtWrVqU6p+qE2NaopW1ShFv4RWqxStCKoIqVmjgiBGjARZcu/798eVy22GJPcmnyT39Xw87iPu+Zzce+Imua+cqRIRAREREZEC1Eo3gIiIiCwXgwgREREphkGEiIiIFMMgQkRERIphECEiIiLFMIgQERGRYhhEiIiISDEMIkRERKSYIko3IDM6nQ43b96Evb09VCqV0s0hIiKiLBARPHr0CGXLloVanXmfR74OIjdv3oSHh4fSzSAiIqIciIqKQrly5TKtk6+DiL29PQD9F+Lg4KBwa4iIiCgr4uLi4OHhYXgfz0y+DiKpwzEODg4MIkRERAVMVqZVcLIqERERKYZBhIiIiBSTr4dmiIgob+l0OiQnJyvdDCoArK2tX7oiJisYRIiICACQnJyMyMhI6HQ6pZtCBYBarYaPjw+sra1NehwGESIigoggOjoaVlZW8PDwMMtfulR4pe7zFR0dDU9PT5P2+mIQISIipKSkID4+HmXLloVGo1G6OVQAODs74+bNm0hJSUHRokVz/DiMvEREBK1WCwAmd7OT5Uj9Xkn93skpBhEiIjLgcRqUVeb6XuHQjLnotMDdMCAhGrBzA5wDALWV0q0iIiLK19gjYg5RIcBP3sDe5sChnvqPP3nry4mIqMDat28fVCoVHj58mOXP8fb2xuLFi3OtTYUNg4ipokKAsK5A/HXj8vgb+nKGESKiXNOnTx+oVCoMGjQozbUhQ4ZApVKhT58+ed8wyjIGEVPotED4CACSzsVnZeEj9fWIiCyBTgvc3gdc2aD/mAe//zw8PLBx40YkJCQYyhITE7FhwwZ4enrm+vOTaRhETHE3LG1PiBEB4qP09YiICjuFhqn9/Pzg6emJkJDnzxMSEgIPDw/UqVPHUJaUlIThw4ejTJkysLW1xauvvoqjR48aPdaOHTtQuXJl2NnZoXnz5rhy5Uqa5zt06BBee+012NnZwcPDA8OHD8eTJ08ybN/UqVPh6ekJGxsblC1bFsOHDzf9iy5EGERMkRBt3npERAWVwsPU77//PlatWmW4/+2336Jv375GdcaPH48tW7ZgzZo1OH78OCpWrIi2bdvi/v37+i8hKgpBQUHo0KEDIiIi0L9/f0yYMMHoMU6dOoW2bdsiKCgIJ0+exKZNm3DgwAEMGzYs3XZt3rwZixYtwldffYWLFy9i27ZtqFmzppm/+oKNQcQUdm7mrUdEVBDlg2Hq3r1748CBA7hy5QquXr2KgwcPolevXobrT548wbJlyzB//ny0b98evr6+WLFiBezs7LBy5UoAwLJly1C+fHksWrQIVapUwTvvvJNmfsn8+fPRs2dPjBw5EpUqVULjxo2xZMkSrF27FomJiWnade3aNbi6uqJVq1bw9PREgwYNMGDAgFz7fyiIGERM4RwAaMoByGgttQrQeOjrEREVVvlgmLp06dLo2LEj1qxZg1WrVqFjx44oXbq04fq///6Lp0+fokmTJoayokWLokGDBjh37hwA4Ny5c2jUqJHR/hj+/v5GzxMeHo7Vq1ejePHihlvbtm2h0+kQGRmZpl3dunVDQkICypcvjwEDBmDr1q1ISUkx95dfoHEfEVOorYC6n+u7HaGC8V8Dz76R6y7mfiJEVLjlk2Hqvn37GoZIvvzyS6NrIvrfz//dhEtEDGWpdTKj0+nwwQcfpDvPI72JsR4eHjh//jx2796NPXv2YMiQIZg/fz5CQ0NN2ha9MGGPiKk8goCAzYDG3bhcU05f7hGkTLuIiPJKPhmmbteuHZKTk5GcnIy2bdsaXatYsSKsra1x4MABQ9nTp09x7NgxVKtWDQDg6+uLw4cPG33ef+/7+fnhzJkzqFixYppbRtvj29nZoXPnzliyZAn27duHP//8E6dOnTLHl1wosEfEHDyCAPcu3FmViCxT6jB1/A2kP09Epb+ey8PUVlZWhmEWKyvj37/FihXD4MGDMW7cODg5OcHT0xPz5s1DfHw8+vXrBwAYNGgQFixYgNGjR+ODDz4wDMO86KOPPkKjRo0wdOhQDBgwAMWKFcO5c+ewe/dufPHFF2natHr1ami1WjRs2BAajQbfffcd7Ozs4OXllTv/CQUQe0TMRW0FuDQDvN/Wf2QIISJLkTpMDSDtnLm8HaZ2cHCAg4NDutfmzJmDN998E71794afnx8uXbqEXbt2oWTJkgD0QytbtmzB9u3bUbt2bSxfvhyzZs0yeoxatWohNDQUFy9eREBAAOrUqYPJkyfDzS393p4SJUpgxYoVaNKkCWrVqoW9e/di+/btKFWqlHm/8AJMJVkZFFNIXFwcHB0dERsbm+E3FhERmS4xMRGRkZHw8fGBra1tzh4kKkS/eubFiasaD30I4TB1oZPZ90x23r85NENERObBYWrKAQYRIiIyn9RhaqIs4hwRIiIiUgyDCBERESmGQYSIiIgUwyBCREREimEQISIiIsUwiBAREZFiGESIiMhs4pNT4D3hF3hP+AXxyTxlll6OQYSIiCyCt7c3Fi9erHQzzGbfvn1QqVR4+PCh0k0xCYMIERGZjVb3/NSQI5H3je7npqioKPTr1w9ly5aFtbU1vLy8MGLECNy7dy9Pnj+3NWvWDCNHjjQqa9y4MaKjo+Ho6KhMo8yEQYSIiMxi5+lotFoYarjfZ9VRvDr3d+w8HZ2rz3v58mXUq1cPFy5cwIYNG3Dp0iUsX74ce/fuhb+/P+7fv5+rz58RrVYLnU6Xa49vbW0NV1dXqFT/PWiwYGEQISIik+08HY3B647jdlySUfmt2EQMXnc8V8PI0KFDYW1tjd9++w1NmzaFp6cn2rdvjz179uDGjRuYNGmSoe6jR4/Qs2dPFC9eHGXLlsUXX3xh9FhTp06Fp6cnbGxsULZsWQwfPtxwLTk5GePHj4e7uzuKFSuGhg0bYt++fYbrq1evRokSJfDzzz/D19cXNjY2WLFiBWxtbdMMnwwfPhxNmzYFANy7dw9vv/02ypUrB41Gg5o1a2LDhg2Gun369EFoaCg+//xzqFQqqFQqXLlyJd2hmS1btqB69eqwsbGBt7c3FixYYPS83t7emDVrFvr27Qt7e3t4enri66+/Nvoahw0bBjc3N9ja2sLb2xuzZ8/O9muSHQwiRERkEq1OMG37WaQ3CJNaNm372VwZprl//z527dqFIUOGwM7Ozuiaq6sr3nnnHWzatAmpB83Pnz8ftWrVwvHjxzFx4kSMGjUKu3fvBgBs3rwZixYtwldffYWLFy9i27ZtqFmzpuHx3n//fRw8eBAbN27EyZMn0a1bN7Rr1w4XL1401ImPj8fs2bPxzTff4MyZM+jVqxdKlCiBLVu2GOpotVr88MMPeOeddwDoT7GtW7cufv75Z5w+fRoDBw5E79698ddffwEAPv/8c/j7+2PAgAGIjo5GdHQ0PDw80vxfhIeHo3v37njrrbdw6tQpTJ06FZMnT8bq1auN6i1YsAD16tXDiRMnMGTIEAwePBj//PMPAGDJkiX46aef8MMPP+D8+fNYt24dvL29c/jqZJHk0KxZs6RevXpSvHhxcXZ2li5dusg///xjVEen08mUKVPEzc1NbG1tpWnTpnL69OksP0dsbKwAkNjY2Jw2k4iIsiAhIUHOnj0rCQkJ2f7cQ5dixOujn196O3QpxuztPnz4sACQrVu3pnt94cKFAkBu374tXl5e0q5dO6PrPXr0kPbt24uIyIIFC6Ry5cqSnJyc5nEuXbokKpVKbty4YVTesmVLmThxooiIrFq1SgBIRESEUZ3hw4dLixYtDPd37dol1tbWcv/+/Qy/rg4dOsiYMWMM95s2bSojRowwqvPHH38IAHnw4IGIiPTs2VNat25tVGfcuHHi6+truO/l5SW9evUy3NfpdFKmTBlZtmyZiIh8+OGH0qJFC9HpdBm2LVVm3zPZef/OcY9IaGgohg4disOHD2P37t1ISUlBmzZt8OTJE0OdefPmYeHChQgODsbRo0fh6uqK1q1b49GjRybGJyIiyi/uPEo0az1zkmc9IanzKPz9/Y2u+/v749y5cwCAbt26ISEhAeXLl8eAAQOwdetWpKTolyAfP34cIoLKlSujePHihltoaCj+/fdfw+NZW1ujVq1aRs/xzjvvYN++fbh58yYAYP369ejQoQNKliwJQN9DMnPmTNSqVQulSpVC8eLF8dtvv+HatWvZ+lrPnTuHJk2aGJU1adIEFy9ehFarNZS92D6VSgVXV1fcuXMHgH4YKCIiAlWqVMHw4cPx22+/ZasNOZHjILJz50706dMH1atXR+3atbFq1Spcu3YN4eHhAPQv/uLFizFp0iQEBQWhRo0aWLNmDeLj4/H999+b7QsgIiJllbG3NWu97KhYsSJUKhXOnj2b7vV//vkHJUuWROnSpTN8jNSQ4uHhgfPnz+PLL7+EnZ0dhgwZgtdeew1Pnz6FTqeDlZUVwsPDERERYbidO3cOn3/+ueGx7Ozs0kwebdCgASpUqICNGzciISEBW7duRa9evQzXFyxYgEWLFmH8+PH4/fffERERgbZt2yI5OTlb/xcikua5U4PYi4oWLZrm60+dVOvn54fIyEhMnz4dCQkJ6N69O7p27ZqtdmRXEXM9UGxsLADAyckJABAZGYlbt26hTZs2hjo2NjZo2rQpDh06hA8++CDNYyQlJSEp6flEp7i4OHM1j4iIckkDHye4OdriVmxiuvNEVABcHW3RwMfJ7M9dqlQptG7dGkuXLsWoUaOM5oncunUL69evx7vvvmt4gz58+LDR5x8+fBhVq1Y13Lezs0Pnzp3RuXNnDB06FFWrVsWpU6dQp04daLVa3LlzBwEBAdluZ8+ePbF+/XqUK1cOarUaHTt2NFwLCwtDly5dDOFEp9Ph4sWLqFatmqGOtbW1Ua9Genx9fXHgwAGjskOHDqFy5cqwsrLKclsdHBzQo0cP9OjRA127dkW7du1w//59w/u7uZllsqqIYPTo0Xj11VdRo0YNAPpvAABwcXExquvi4mK49l+zZ8+Go6Oj4ZbeZBwiIspfrNQqTOnkC0AfOl6Uen9KJ19YqXNnmWlwcDCSkpLQtm1b7N+/H1FRUdi5cydat24Nd3d3zJw501D34MGDmDdvHi5cuIAvv/wS//vf/zBixAgA+lUvK1euxOnTp3H58mV89913sLOzg5eXFypXrox33nkH7777LkJCQhAZGYmjR49i7ty52LFjx0vb+M477+D48eOYOXMmunbtClvb571DFStWxO7du3Ho0CGcO3cOH3zwQZr3SW9vb/z111+4cuUKYmJi0l0WPGbMGOzduxfTp0/HhQsXsGbNGgQHB2Ps2LFZ/r9ctGgRNm7ciH/++QcXLlzA//73P7i6uqJEiRJZfozsMksQGTZsGE6ePGm03ChVet1EGa15njhxImJjYw23qKgoczSPiIhyWbsabljWyw9lHGyMyl0dbbGslx/a1XDLteeuVKkSjh07hgoVKqBHjx6oUKECBg4ciObNm+PPP/80+kt+zJgxCA8PR506dTB9+nQsWLAAbdu2BQCUKFECK1asQJMmTVCrVi3s3bsX27dvR6lSpQAAq1atwrvvvosxY8agSpUq6Ny5M/76668s/dFcqVIl1K9fHydPnjSslkk1efJk+Pn5oW3btmjWrBlcXV3x+uuvG9UZO3YsrKys4OvrC2dn53Tnj/j5+eGHH37Axo0bUaNGDfzf//0fPv30U/Tp0yfL/5fFixfH3LlzUa9ePdSvXx9XrlzBjh07oFbn3iJblaQ3gJQNH374IbZt24b9+/fDx8fHUH758mVUqFABx48fR506dQzlXbp0QYkSJbBmzZqXPnZcXBwcHR0RGxsLBwcHU5pJRESZSExMRGRkJHx8fIz+Ws+uR4lPUXOqfoLj6vfrI6CSc671hJCyMvueyc77d44jjohg2LBhCAkJwe+//24UQgDAx8cHrq6uhvXZgH6jlNDQUDRu3DinT0tERPnYi6GjgY8TQwi9VI4nqw4dOhTff/89fvzxR9jb2xvGsxwdHQ2zhkeOHIlZs2ahUqVKqFSpEmbNmgWNRoOePXua7QsgIqL8Q2NdBFfmdHx5RaJnchxEli1bBkB/EM+LVq1aZRiPGj9+PBISEjBkyBA8ePAADRs2xG+//QZ7e/scN5iIiIgKjxwHkaxMLVGpVJg6dSqmTp2a06chIiKiQoxnzRAREZFiGESIiMjAxIWUZEHM9b3CIEJERIadN7O7rThZrtTvlezs2poes23xTkREBVeRIkWg0Whw9+5dFC1aNFc3sKKCT6fT4e7du9BoNChSxLQowSBCRERQqVRwc3NDZGQkrl69qnRzqABQq9Xw9PTMcLf0rGIQISIiAPqD1SpVqsThGcoSa2trs/ScMYgQEZGBWq02aYt3ouziICAREREphkGEiIiIFMMgQkRERIphECEiIiLFMIgQERGRYhhEiIiISDEMIkRERKQYBhEiIiJSDIMIERERKcYig0h8cgq8J/wC7wm/ID45RenmEBERWSyLDCJERESUPzCIEBERkWIYRIiIiEgxDCJERESkGAYRIiIiUgyDCBERESmGQYSIiIgUwyBCREREimEQISIiIsUwiBAREZFiGESIiIhIMUWUbkChodMCd8OAhGjAzg1wDgDUVkq3ioiIKF9jEDGHqBAgfAQQf/15maYcUPdzwCNIuXYRERHlcxyaMVVUCBDW1TiEAED8DX15VIgy7SIiIioAGERModPqe0Ig6Vx8VhY+Ul+PiIiI0mAQMcXdsLQ9IUYEiI/S1yMiIqI0GERMkRBt3npEREQWhkHEFHZu5q1HRERkYRhETOEcoF8dA1UGFVSAxkNfj4iIiNJgEDGF2kq/RBdA2jDy7H7dxdxPhIiIKAMMIqbyCAICNgMad+NyTTl9OfcRISIiyhA3NDMHjyDAvQt3ViUiIsomBhFzUVsBLs2UbgUREVGBwqEZIiIiUgyDCBERESmGQYSIiIgUwyBCREREimEQISIiIsUwiBAREZFichxE9u/fj06dOqFs2bJQqVTYtm2b0fU+ffpApVIZ3Ro1amRqe4mIiKgQyXEQefLkCWrXro3g4OAM67Rr1w7R0dGG244dO3L6dERERFQI5XhDs/bt26N9+/aZ1rGxsYGrq2tOn4KIiIgKuVydI7Jv3z6UKVMGlStXxoABA3Dnzp1M6yclJSEuLs7oRkRERIVXrgWR9u3bY/369fj999+xYMECHD16FC1atEBSUlKGnzN79mw4Ojoabh4eHrnVPPPTaYHb+4ArG/QfdVqlW0RERJTv5dpZMz169DD8u0aNGqhXrx68vLzwyy+/ICgo/RNpJ06ciNGjRxvux8XFFYwwEhUChI8A4q8/L9OUA+p+ztN3iYiIMpFnh965ubnBy8sLFy9ezLCOjY0NbGxs8qpJ5hEVAoR1BSDG5fE39OUBmxlGiIiIMpBn+4jcu3cPUVFRcHNzy6unzH06rb4n5L8hBHheFj6SwzREREQZyHEQefz4MSIiIhAREQEAiIyMREREBK5du4bHjx9j7Nix+PPPP3HlyhXs27cPnTp1QunSpfHGG2+Yq+3KuxtmPByThgDxUfp6RERElEaOh2aOHTuG5s2bG+6nzu147733sGzZMpw6dQpr167Fw4cP4ebmhubNm2PTpk2wt7c3vdX5RUK0eesRERFZmBwHkWbNmkEkvSEJvV27duX0oQsOuywOM2W1HhERkYWxyLNmtLrnAepI5H2j+9niHKBfHQNVBhVUgMZDX4+IiIjSsLggsvN0NFotDDXc77PqKF6d+zt2ns7B8InaSr9EF0DaMPLsft3F+npERESUhkUFkZ2nozF43XHcjjPeVO1WbCIGrzueszDiEaRfoqtxNy7XlOPSXSIiopfIs31ElKbVCaZtP5vhQlsVgGnbz6K1ryus1BkNtWTAIwhw76JfHZMQrZ8T4hzAnhAiIqKXsJggciTyPqJjEzO8LgCiYxNxJPI+/CuUyv4TqK0Al2Y5bh8REZElspihmTuPMg4hOalHREREprOYIFLG3tas9YiIiMh0FhNEGvg4wc3RNrOFtnBztEUDH6e8bBYREZFFs5ggYqVWYUonXwAZLrTFlE6+2Z+oSkRERDlmMUEEANrVcMOyXn4o42B8wq+roy2W9fJDuxrcAZWIiCgvWcyqmVTtarihScXSqDn1NwDA6vfrI6CSM3tCiIiIFGBxQQSAUeho4ONknhCi03IfESIiomyyyCBidlEhQPgIIP768zJNOf3279xZlYiIKEMWNUckV0SFAGFdjUMIoL8f1lV/nYiIiNLFIGIKnVbfE5LuxvHQl4eP1NcjIiKiNBhETHE3LG1PyH/FR+nrERERURoMIqaIv2HeekRERBaGQcQUSXfNW4+IiMjCMIiYwsbZvPWIiIgsDIOIKTTu5q1HRERkYRhETOEcoN8vJDMaD309IiIiSoNBxBRqK/2mZVAh/aP0VEDdxdxhlYiIKAMMIqbyCAICNqcdftGU05dzZ1UiIqIMcYt3c/AIAty78KwZIiKibGIQMRe1FeDSTOlWEBERFSgMIubC03eJiIiyjUHEHKJCgKMfAok3n5fZlgXqf8E5IkRERJngZFVTRYUAYW8ahxBAfz/sTZ6+S0RElAkGEVPotMCf72Ve58/3ePouERFRBhhETHF7L5DyOPM6KY/19YiIiCgNBhFTRH5n3npEREQWhkHEFC/rDcluPSIiIgvDIGKK0q+atx4REZGFYRAxReUPkfaMmf9SPatHRERE/8UgYgq1FVCkWOZ1ihTjxmZEREQZYBAxxd2wrK2auRuWN+0hIiIqYBhETBF/w7z1iIiILAyDiCmS7pq3HhERkYVhEDGFjbN56xEREVkYBhFTaNzNW4+IiMjCMIiYwjkA0JTLvI7GQ1+PiIiI0mAQMYXaCvB6O/M6Xm9x+S4REVEGGERModMCVzdkXufqRp6+S0RElAEGEVPcDQPir2deJz6K+4gQERFlgEHEFAnR5q1HRERkYRhETGHnZt56REREFoZBxBTOAYB1qczrWJfiqhkiIqIM5DiI7N+/H506dULZsmWhUqmwbds2o+sigqlTp6Js2bKws7NDs2bNcObMGVPbW/C87HBeIiIiC5bjIPLkyRPUrl0bwcHB6V6fN28eFi5ciODgYBw9ehSurq5o3bo1Hj16lOPG5jt3w4Dke5nXSbrHyapEREQZKJLTT2zfvj3at2+f7jURweLFizFp0iQEBQUBANasWQMXFxd8//33+OCDD3L6tPkLJ6sSERGZJFfmiERGRuLWrVto06aNoczGxgZNmzbFoUOHMvy8pKQkxMXFGd3yNU5WJSIiMkmOe0Qyc+vWLQCAi4uLUbmLiwuuXr2a4efNnj0b06ZNy40mGdFYF8GVOR1Nf6DUyaqZDc/YcLIqERFRRnJ11YxKZTxTU0TSlL1o4sSJiI2NNdyioqJys3nmoUvK/Lr2JdeJiIgsWK4EEVdXVwDPe0ZS3blzJ00vyYtsbGzg4OBgdMvXbu8DUh5nXiflsb4eERERpZErQcTHxweurq7YvXu3oSw5ORmhoaFo3LhxbjylMu7sM289IiIiC5PjOSKPHz/GpUuXDPcjIyMREREBJycneHp6YuTIkZg1axYqVaqESpUqYdasWdBoNOjZs6dZGk5EREQFX46DyLFjx9C8eXPD/dGjRwMA3nvvPaxevRrjx49HQkIChgwZggcPHqBhw4b47bffYG9vb3qr8wuXZsCZGVmrR0RERGmoRESUbkRG4uLi4OjoiNjY2Pw5X0SnBUJcMl81Y10KCLoNqK3yrl1EREQKys77N8+aMYXaCmj4deZ1Gn7NEEJERJQBBhFTeQQBAVsAO3fjcrty+nKPIGXaRUREVADkyoZmFscjCHDvoj9TJiFav5OqcwB7QoiIiF6CQcRc1FaclEpERJRNHJohIiIixTCIEBERkWIYRIiIiEgxDCJERESkGAYRIiIiUgyDCBERESmGQYSIiIgUwyBCREREiuGGZuai03JnVSIiomxiEDGHqBAgfAQQf/15maYcUPdznjVDRESUCQ7NmCoqBAjrahxCACD+hr48KkSZdhERERUADCKm0Gn1PSGQdC4+Kwsfqa9HREREaTCImOJuWNqeECMCxEfp6xEREVEaDCKmSIg2bz0iIiILwyBiCjs389YjIiKyMAwipijVGFC9ZImuykpfj4iIiNJgEDHFvUOAvGQiqmj19YiIiCgNBhFTcI4IERGRSRhETGFdyrz1iIiILAyDiCliT5m3HhERkYVhEDHF4yvmrUdERGRhGERMYV/BvPWIiIgsDIOIKSoOydry3YpD8qY9REREBQyDiCmKWANlAzOvUzZQX4+IiIjSYBAxhU4LPAjPvM6D4zz0joiIKAMMIqZ46aF34KF3REREmWAQMQU3NCMiIjIJg4gpeOgdERGRSRhETOEcAGjKZV5H46GvR0RERGkwiJhCbQV4vZ15Ha+39PWIiIgoDQYRU+i0wNUNmde5upGrZoiIiDLAIGIKrpohIiIyCYOIKbhqhoiIyCQMIqbgqhkiIiKTMIiYwrBqRpVBBRVXzRAREWWCQcQUaiug7ufP7vw3jDy7X3cxV80QERFlgEHEVB5BQMBmQONuXK4ppy/3CFKmXURERAVAEaUbUCh4BAHuXfSrYxKi9XNCnAPYE0JERPQSDCLmorYCXJop3QoiIqIChUMzREREpBj2iJiLTsuhGSIiomxiEDGHqBAgfITxLquacvoVNZysmj8xOBIR5Qu5OjQzdepUqFQqo5urq2tuPmXeiwoBwrqm3eo9/oa+PCpEmXZRxqJCgJ+8gb3NgUM99R9/8uZrRUSkgFyfI1K9enVER0cbbqdOncrtp8w7Oq2+JwSSzsVnZeEjeehdfpJhcLzO4EhEpIBcH5opUqRI4esFSfXSQ+/k+aF3XFGjvEyDI/Tl4SP1S7E5TENElCdyvUfk4sWLKFu2LHx8fPDWW2/h8uXLGdZNSkpCXFyc0S1f46F3BQtPSyYiyndyNYg0bNgQa9euxa5du7BixQrcunULjRs3xr1799KtP3v2bDg6OhpuHh4eudk80/HQu4LlSZR56xERkclUIpJRP7XZPXnyBBUqVMD48eMxevToNNeTkpKQlJRkuB8XFwcPDw/ExsbCwcEhr5qZdTqtfpJj/A2k392v0q+e6RzJrv784Ogw4OKXL69XaShQPzj320NEVEjFxcXB0dExS+/febp8t1ixYqhZsyYuXryY7nUbGxvY2NjkZZNMk3roXVhX6A+5ezGM8NC7/CermTvPsjkRkcXL051Vk5KScO7cObi5FaKhCh56V3DYVzJvPSIiMlmuDs2MHTsWnTp1gqenJ+7cuYMZM2YgNDQUp06dgpeX10s/PztdO4rjBln5X0oy8D8NIJksp1ZZAd3igSLWedcuIqJCJt8MzVy/fh1vv/02YmJi4OzsjEaNGuHw4cNZCiEFDg+9y/+KWANVRwPn5mdcp+pohhAiojyUq0Fk48aNufnwRNlXZ57+4z8LjXtGVFb6EJJ6nYiI8gTPmiHLU2ceUHMGcGkp8OhfwL4CUHEIe0KIiBTAIEKWqYg1UHWk0q0gIrJ4DCLmwsmqRERE2cYgYg5RIcCxEUDCC9uH25UD6n3O5btERESZyNN9RAqlqBAg7E3jEALo74e9ydNciYiIMsEgYgqdFvhrYOZ1jgzU16MciU9OgfeEX+A94RfEJ6co3RwiIjIzBhFT3N4HJKd/gJ9B0j19PSIiIkqDQcQUt383bz0iIiILwyBiivhr5q1HRERkYRhETGFXzrz1KA2t7vlRSEci7xvdN4lOqx8yu7JB/5HzeIiIFMHlu6awLW3eemRk5+loTPnpjOF+n1VH4eZoiymdfNGuhgknOEeFAOEjgPgXVjppygF1udyaiCivsUfEFLau5q1HBjtPR2PwuuO4HZdkVH4rNhGD1x3HztPROXvgqBAgrKtxCAGA+Bv6ci63JiLKUwwiptC4m7ceAdAPx0zbfhbpDcKklk3bfjb7wzQ6rb4nJLNHDh/JYRoiojzEIGKKUo31p7ZmRmWlr0dZdiTyPqJjEzO8LgCiYxNxJPJ+9h74bljanpD/PnJ8lL4eERHlCQYRU9w7ZHyUfHpEq69HWXbnUcYhJCf1DBKyOJyT1XpERGQyBhFT8I0tV5SxtzVrPQO7LE5wzWo9IiIyGYOIKfjGlisa+DjBzdEWqgyuqwC4OdqigY9T9h7YOUC/OiazR9Z46OsREVGeYBAxBd/YcoWVWoUpnXwBpP2fTb0/pZMvrNQZ/b9nQG2lX6Kb2SPXXayvR0REeYJBxBR8Y8s17Wq4YVkvP5RxsDEqd3W0xbJefjnfR8QjCAjYnHYlk6acvpz7iBAR5SmViJhpq0rzi4uLg6OjI2JjY+Hg4KB0czKW7gZZHvoQwjc2kzxKfIqaU38DAKx+vz4CKjlnvyckPTqtfnVMQrR+6Mw5gIGRiMhMsvP+zZ1VzcEjCHDvwje2XPBi6Gjg42SeEALoXxuXZuZ5LCIiyjEGEXPhGxsREVG2MYhQvqaxLoIrczqa/4E5NENElC8wiJDl4aF3RET5BlfNkGXhoXdERPkKgwhZDh56l6vik1PgPeEXeE/4BfHJKUo3h4gKCAYRshw89I6IKN9hECHLwbOBiIjyHQYRshw8G4iIKN9hECHLUaoxoHrJEl2Vlb4eERHlCQYRshz3DgHykomootXXIyKiPMEgQpaDc0SIiPIdBhGyHJwjQkSU7zCIkOVwDtDvoIqMDs5T6U9Ndg7Iy1YREVk0BhGyHGor/TbuANKGkWf36y7mmTM5pNU93yjuSOR9o/tERBlhECHL4hEEBGwGNO7G5Zpy+nKeNZMjO09Ho9XCUMP9PquO4tW5v2Pnac63IaLMqUQk3/7ZEhcXB0dHR8TGxsLBwUHp5lBhwtN3zWbn6WgMXnc8zcb5qX1Oy3r5oV0NzrshsiTZef/m6btkmdRWgEszpVtR4Gl1gmnbz2Z4eo8KwLTtZ9Ha1xVW6ozm5hCRJePQDBHl2JHI+4iOTczwugCIjk3Ekcj7edcoIipQGESIKMfuPMo4hOSkHhFZHgYRIsqxMva2Zq1HRJaHc0SIKMca+DjBzdEWt2IT050nogLg6miLBj5OOX+SlGTg0lLg0b+AfQWg4hCgiHXOH4+ogNHqBEci7+POo0SUsdf/PBWmOVcMIkSUY1ZqFaZ08sXgdcehAozCSOqvySmdfHP+S/PEeODcAgC652XHxwDVxgB15uXsMYkKkJ2nozFt+1mjuVhujraY0sm30KxG49AMEZmkXQ03LOvlhzIONkblro62pi3dPTEeODcfRiEE0N8/N19/nagQS10a/98J4bdiEzF43fFCs08P9xEhIrN4lPgUNaf+BgBY/X59BFRyznlPSEoy8IMd0oaQF6mB7gkcpqFCSasTvDr39wxXpaUOex74qEW+HKbJzvs3e0SIyCxe/GVo8hj2xWBkHkKgv34xOOfPQZSPWdLSeAYRIsp/7oSZtx5RAZMnS+N1WuD2PuDKBv1HnTbnj2WCPAkiS5cuhY+PD2xtbVG3bl2EhfGXBxFlokgx89YjKmByfWl8VAjwozewtzlwqKf+44/e+vI8lutBZNOmTRg5ciQmTZqEEydOICAgAO3bt8e1a9dy+6mJqKAqUdu89YgKmNSl8RkNcKqgXz2To6XxUSFA2JtAwnXj8oTr+vI8DiO5HkQWLlyIfv36oX///qhWrRoWL14MDw8PLFu2LLefmogKKjtX89YjKmBSl8YDSBNGTFoar9MCfw3MvM6RgXk6TJOrQSQ5ORnh4eFo06aNUXmbNm1w6NChNPWTkpIQFxdndCMiC5Rwy7z1iAqg1KXxro7Gwy8mLY2/vQ9Ivpd5naR7+np5JFc3NIuJiYFWq4WLi4tRuYuLC27dSvsLZPbs2Zg2bVpuNomICoL74eatR1RAtavhhta+rubbWTX6t6zXc2uZs+fIpjyZrKpSGf+HiUiaMgCYOHEiYmNjDbeoqKi8aB4R5TcPTpm3HlEBZqVWwb9CKXR5xR3+FUqZtjQ+O0Ekj+Rqj0jp0qVhZWWVpvfjzp07aXpJAMDGxgY2NjZpyonIwujizVuPiPSeZHGhSFbrmUGu9ohYW1ujbt262L17t1H57t270bhx49x8aiLKYxrrIrgypyOuzOkIjbWJf+PYZnESalbrEZGe9ol565lBrh96N3r0aPTu3Rv16tWDv78/vv76a1y7dg2DBg3K7acmooKq5CvA/cNZq0dEWScv27E4m/XMINeDSI8ePXDv3j18+umniI6ORo0aNbBjxw54eXnl9lMTUUHl3Bj4d3nW6hFR1hV1AJ6+ZNVMar08kutBBACGDBmCIUOG5MVTEVFhUMzDvPWISM/jdeDyyqzVyyM8a4aI8h/nAEBTLvM6Gg99PSLKOr8vzFvPDBhEiCj/UVsBdT+Hfg/J9PaVVAF1F+vrEVHWWdsB7l0yr+PeRV8vjzCIEFH+5BEEBGwGNO7G5Zpy+nKPIGXaRVTQNd2WcRhx76K/nodUIiJ5+ozZEBcXB0dHR8TGxsLBIe8mzhBRPqLTAnfDgIRowM5NPxzDnhAi0yUnAH+PAx5dBOwrAbXnm60nJDvv33kyWZWIKMfUVoBLM6VbQVT4WNsB9YOVbgWHZoiIiEg5DCJERESkGAYRIiIiUgyDCBERESmGQYSIiIgUwyBCREREimEQISIiIsUwiBAREZFiGESIiIhIMQwiREREpBgGESIiIlIMgwgREREphkGEiIiIFMMgQkRERIphECEiIiLFMIgQERGRYhhEiIiISDEMIkRERKQYBhEiIiJSDIMIERERKYZBhIiIiBTDIEJERESKYRAhIiIixTCIEBERkWIYRIiIiEgxDCJERESkmCJKN4CIiAoJnRa4GwYkRAN2boBzAKC2UrpVlM8xiBARkemiQoDwEUD89edlmnJA3c8BjyDl2kX5HodmiIjINFEhQFhX4xAC6O+HddVfJ8oAgwgREeWcTqvvCYFkUEGA8JH6ekTpYBAhIqKcuxuWtifkv+Kj9PWI0sEgQkREORd/w7z1yOIwiBARUc4l3TVvPbI4DCJERJRzNs7mrUcWh0GEiIhyTuNu3npkcRhEiIgo55wD9PuFZEbjoa9HlA4GESIiyjm1lX7TMqie3V70rKzuYu6wShliECEiItN4BAEBm9MOv2jK6cu5syplglu8ExGR6TyCAPcuPGuGso1BhIiIzENtBbg0U7oVVMBwaIaIiIgUk6tBxNvbGyqVyug2YcKE3HxKIiIiKkByfWjm008/xYABAwz3ixcvnttPSURERAVErgcRe3t7uLq65vbTEBERUQGU63NE5s6di1KlSuGVV17BzJkzkZycnGHdpKQkxMXFGd2IiIio8MrVHpERI0bAz88PJUuWxJEjRzBx4kRERkbim2++Sbf+7NmzMW3atNxsEhERAYhPToHv/+0CAJz9tC001lxEScpQiYhk5xOmTp360rBw9OhR1KtXL035li1b0LVrV8TExKBUqVJpriclJSEpKclwPy4uDh4eHoiNjYWDg0N2mklERJlgEKHcFBcXB0dHxyy9f2f7O2/YsGF46623Mq3j7e2dbnmjRo0AAJcuXUo3iNjY2MDGxia7TSIiIqICKttBpHTp0ihdunSOnuzEiRMAADc3txx9PhERERUuudYX9+eff+Lw4cNo3rw5HB0dcfToUYwaNQqdO3eGp6dnbj0tERERFSC5FkRsbGywadMmTJs2DUlJSfDy8sKAAQMwfvz43HpKIiIiKmByLYj4+fnh8OHDufXwREREVAjwrBkiIguk1T1fMHkk8r7RfaK8xCBCRGRhdp6ORquFoYb7fVYdxatzf8fO09EKtoosFYMIEZEF2Xk6GoPXHcftuCSj8luxiRi87jjDCOU5BhEiIguh1QmmbT+L9AZhUsumbT/LYRrKUwwiREQW4kjkfUTHJmZ4XQBExybiSOT9vGsUWTwGESIiC3HnUcYhJCf1iMyBQYSIyEKUsbc1az0ic2AQISKyEA18nODmaAtVBtdVANwcbdHAxykvm0UWjkGEiMhCWKlVmNLJFwDShJHU+1M6+cJKnVFUeQmdFri9D7iyQf9Rp81hS8mSMIgQEVmQdjXcsKyXH8o4GJ907upoi2W9/NCuRg4PJY0KAX7yBvY2Bw711H/8yVtfTpQJlYjk23VacXFxcHR0RGxsLBwcHJRuDhFRofEo8SlqTv0NALD6/foIqOSc856QqBAgrCuQZmHws8cL2Ax4BOW4rVTwZOf9mz0iREQW6MXQ0cDHybThmPARSBtC8LwsfCSHaShDDCJERJRzd8OA+OuZVBAgPkpfjygdDCJERJRzCVncEj6r9cjiMIgQEVHO2WVxcmtW65HFYRAhIqKccw4ANOWQdkFwKhWg8dDXI0pHEaUbQEREeU9jXQRX5nQ0/YHUVkDdz5+tmlHBeNLqs3BSd7G+HlE62CNCRESm8QjSL9HVuBuXa8px6S69FHtEiIjIdB5BgHsX/eqYhGj9nBDnAPaE0EsxiBARkXmorQCXZkq3ggoYDs0QERGRYhhEiIiISDEMIkRERKQYBhEiIiJSDIMIERERKYZBhIiIiBTDIEJERESKYRAhIiIixTCIEBERkWIYRIiIiEgxDCJERESkGAYRIiIiUky+PvRORAAAcXFxCreEiIiIsir1fTv1fTwz+TqIPHr0CADg4eGhcEuIiIgoux49egRHR8dM66gkK3FFITqdDjdv3oS9vT1UKpVZHzsuLg4eHh6IioqCg4ODWR+bzIuvVcHB16pg4etVcBS010pE8OjRI5QtWxZqdeazQPJ1j4harUa5cuVy9TkcHBwKxItKfK0KEr5WBQtfr4KjIL1WL+sJScXJqkRERKQYBhEiIiJSjMUGERsbG0yZMgU2NjZKN4Vegq9VwcHXqmDh61VwFObXKl9PViUiIqLCzWJ7RIiIiEh5DCJERESkGAYRIiIiUgyDCBERESmGQYSIiIgUwyBChQ4XghERFRz5eov3/EBEzH7ODZnfkydPICLQarVZ3laYiNLS6XQvPRuEyJz43fYfOp0OOp0OT58+hU6nYwgpAM6dO4euXbuiYcOGqF27NrZu3ap0kygbdDqd0k2gZ06dOoV+/fohJiZG6aZQPpLbP6MMIi+4cOEChgwZgldffRV+fn5o164dwsLCkJSUpHTTKAMRERFo2LAhvL29ERQUhNq1a+Ptt9/G7t27lW4aZYFWqzX89b1gwQJ8//33CrfIciUmJiIwMBBr1qxB3759cf/+faWbRHksdVj71KlT2L59O3744Qc8ePAg13vIGESeOXnyJPz9/fHo0SO0bdsWTZs2xd27d9GmTRssWbIEDx48ULqJ9B9nz55Fo0aN8Mknn2DZsmWYPn06vvnmG1SpUgVz5szB06dPlW4iZWDlypUAACsrKyQnJyMhIQHLli2Dp6enwi2zXLa2thg8eDCaNm2K48ePo3379vy9Z2FUKhW2bNmCzp07Y8qUKVi0aBF8fHxw4MCBXH1eBhEAN2/eRLdu3TBgwACsX78eU6ZMQXBwMHbs2IHevXvjk08+wbZt2wDo/4Ij5SUnJ2P27NlITk7GgAEDDGXOzs7w9fVFqVKlYGVlpXArKT0//fQTJk6ciBEjRgAArK2tkZiYiISEBBQtWlTh1lm2atWq4cGDB1i7di3UajXatWvHMGJBjhw5gv79+2PSpEk4fvw4vvnmG8TFxeHQoUOGOrmxGIBBBMCff/4JJycnjBo1CsDz8TA3NzcsXLgQQUFBGD9+PG7fvs03t3zgwYMHsLa2xvDhw9GyZUs0aNAAly9fhrW1NSIjI7F9+3a89tprnHCXTzVu3BgfffQR9u3bh+HDhwMASpYsieLFi6N48eIAgKdPnyIlJQUAV0HlpS5dusDHxwdr1qwxvAl17NiRYcRCXLp0CYGBgejfvz8iIyPRvn17DBo0COPHjwegH75TqVRm/5nkb2oAf//9N2JjY+Hi4gIARm9gGo0G/fv3x5MnT/DXX38p1UR65tatW3j99dexdetW1K9fHzNnzoSnpycCAwNx6NAhtGrVCr1798awYcMA8E0sv4mNjUXp0qXx3nvvoXfv3vjjjz/w4Ycf4tGjR3BycjK8XkWLFkWRIvpFfRxiyx2nTp1C9+7d8csvvyAyMtJQPnDgQDx8+BBubm748ccfcffuXYYRC3H+/Hncvn0bUVFRaNasGdq3b48vv/wSALB161ZMnjwZycnJZl/EwSACoFSpUrh69SouX74MwPjNS61Wo0WLFlCr1bhx44ZSTaRntFotrly5gv/9738AgAYNGmDmzJlwd3fHq6++ikaNGmHZsmXQ6XRcep3PrF27FlWrVkVUVBRKly6Nvn37ok+fPggNDUWPHj1w9uxZDBo0CK1bt0bz5s3RsmVLNGnSBPPmzVO66YVOQkICunXrhs2bN+OLL75Au3btsHz5cly6dAmtW7fG5cuXsXTpUlSuXBk///wz4uLi0KRJEzx8+FDpplMuCggIQEJCAurUqYNWrVrhq6++Mrwf7t+/H9HR0UhOTjb781pkELl37x4iIiJw6NAhiAheeeUVODg4GCalqlQqw1yQlJQUXL58GZUrV0bt2rUVbjm5u7tj9erV+OGHH/DNN98AABo1aoRp06ahQ4cOOHLkCK5fvw61Ws35PPnI8uXL0adPH8TGxhrGm52cnNC3b1+8++67uH37NqytrfH222+jXbt2aNmyJdq2bYtWrVphwoQJCre+8LGzs8OSJUvg7OwMKysrjBkzBitXrsQHH3yAiRMnok+fPvj5558RFRWFKlWq4IcffoC9vT2DSCGRGi7Onj2LgwcP4uTJkwCAhg0bGr4nmjRpAq1Wizt37uDjjz/GunXr8PHHHxuGT83dIIty+vRpadasmbRt21amTZsmSUlJIiLSq1cvsbW1lenTp8vdu3eNPmfy5Mni6+srN2/eVKLJFi8mJkYePHhguP/kyRMZOnSo1KpVS44fP24o/+uvv6RFixZSrVo1uXLligItpfR8/fXXUqRIEdm+fbt07dpV/P39ja7fv39f5s+fL3Xr1pVJkyal+xgpKSl50VSLs3PnTrGxsZFPP/1Uzp8/L3/++ac0bdpUvL29RaVSyblz5wx1k5OTFWwpmduWLVvE3t5eKlasKFZWVjJz5kwREXnw4IEEBgZK9erVpUSJEvLqq6+Kt7e30e9ac7OoIHL69GlxcnKSSZMmyZkzZ9Jc79ixo9jb20vTpk1l06ZNEhwcLMOGDRMHB4dcfREoYzdu3JBSpUpJt27dZO3atYbyPXv2SNWqVWXGjBmi1WoN5UeOHJG6detK3bp1JSUlRXQ6nRLNpme+/PJLUalUsnnzZhERCQsLEzc3N9mwYYOIiOG1u3fvnnz22WdSq1Yt6dmzp2LtLcyuXr0qK1askI8//lgSExMN5T///LPY2NjIkCFDDGX79++Xffv2KdFMykWpvw9v3boltWvXlpUrV8qZM2fk66+/FrVaLWPGjBER/R97R48eleDgYNm7d69ERUXlarssJojExMRIgwYNZNCgQUblWq1Wnj59arg/bdo08ff3F41GI9WrV5fu3bvLqVOn8rq59MzRo0fF09NTmjdvLm+88Ya0a9dOYmNjRURkzpw5YmdnJxcuXDD6nPDwcPaI5AP//vuvBAQEyJYtWwxl0dHR4ufnJwMHDhQR/S/G1DBy//59mTJlivTq1csoXJLpTp8+LbVr15ZBgwbJ0KFDDeWpPU2//PKL2NraSv/+/Y16nxjkC59du3bJjBkzZODAgZKQkGAo37Bhg6jVahk7dqxReV6wmCBy5MgRqVWrlhw+fDjd6//tdoyMjJTk5GSJj4/Pi+ZRJqZPny4uLi5y4cIF6dy5swQEBEhwcLD8+++/0r17dwkICODrlE9dv35dRPRvaKlvauvXr5eiRYvKoUOHDPVSr8XFxRn+zTBiHmfOnBFHR0cZO3as3Lp1y1C+ZcsW2blzp+F3X2oYGTp0KH+eCrG5c+eKSqWS8uXLy+3bt0Xk+c/fxo0bxcbGRoYNGyaPHj3KszZZTBBZvXq1ODo6Gv0g/ldCQoLs2bPH6K80/kWQ9x4+fGg0J0REJDAwUCZMmCAiIsHBwfLuu+9KrVq1ZNCgQVKvXj359ttv+VrlU/99Xa5evSr+/v4yceJEo5+1zD6Hcubhw4fSsmXLND3BM2bMEJVKJe7u7rJnzx5Dr/COHTtEpVLJ6NGjlWgu5ZHUIdOFCxemubZ69WpxcnIyhJS8UKiDyOPHjw3/3rJli1hZWcnp06dFJP3Jb4sXL+YPoMJu3rwp1apVk/fee0/Cw8MN5T/99JN06dJFjh07JiL6Hqu5c+eKg4ODqFQqef31143GvUkZf/31l6xZs0bWrFmT6byqMWPGiIuLi9HPKJnflStXpGrVqvLzzz8byn788UcpUqSIhIaGSvv27cXd3V12795tmLi/e/duo0mqVHClBvqoqCg5ffq0XLp0yfA6z5o1S9RqtXzxxRdpPi8uLi5P21log8iJEyeka9eucunSJRERuX37tlSuXFmaNm0q9+/fFxExvCCphg4dKv/3f//HGfoKmzJlirRs2VIcHBzkiy++kJiYGElKSpK3335bevXqZVQ3NDRU+vXrJ2fPnlWotZRq5cqV4u7uLg0aNBAfHx+pX79+mgmPqb0fMTExUqVKFfnkk0+UaKrF2LVrl6jVaqN5VFFRUXLixAnD/TZt2kjp0qX5M1TIpIaQkJAQqV27tnh5eUlAQIAEBgYagsa8efNErVbL0qVLlWxq4QwiERERUqRIEUNXvoj+F+CMGTPExcVF3nzzTaPEFxsbK5MmTZJy5cqlmfhIeePOnTsSGhoqf/75pyQnJ0tMTIxMnjxZbG1tpUOHDrJ161Z59OiRuLm5SXBwsNHnclmh8rZt2yZOTk6yceNGSUxMlCNHjkinTp1k6tSpIpJ2qCUpKUmaNm0q/fr1U6K5FuPAgQOiVqsNE4ZffB1Sf272798vderUkfPnzyvSRso9e/fuFY1GI19++aXcv39fli1bJiqVSr766itDnfnz54tKpZIVK1Yo1s5CF0QiIiLEzs5OPv744zTXnj59KmPGjJEyZcqIu7u7TJ06VQYNGiRvvvmmlClThkt0FXLy5EmpU6eOeHh4iJ2dnfj7+xv2cvnjjz/kjTfeEFdXV3n//fflk08+kTZt2qS7/JqUce/ePenevbtMnDjRqHzSpEnyyiuvpOlhTH0zjI6OZu9jHvD395caNWoY5l29uEpQRGT06NHSqVMnefjwoQKto9yQOjn8448/Nkw3iI6OFg8PDxk2bJihXur3wuLFixXtEStUQeT06dNib28vkydPNiqfMWOGoezp06cSEhIib731ltSsWVMaNGgg48aN418DComIiJBixYrJ6NGj5fDhw7JkyRKpUKGCtGrVyjB/4ObNmxISEiJVq1YVa2trUalU8uWXX3JCYz7x4MEDmTZtmuzatUtEngeNLVu2pBtERIzfDBlGzOO/Sy5Th8G2bdsmzs7O4ufnJ1evXjVcv3v3rnz00UdSokQJblFQSL311lsybdo0uX79uri7u8vAgQONhmxWr16dL1anFZogkpKSInXr1hVXV1fDhFQR/V4TGo1Gdu7cmeZzYmJiRITLBJVy6dIl0Wg0Mm7cOKPykSNHiqenp9y5c8eoPCkpST788EOpWbOm/PPPP3nZVHqJGzduGP6d+ovuwIEDUq9ePaM3yIyWz5Nprl+/Lt26dZPff//dUJb6ey0hIUFWrVol3t7e4uTkJF27dpU33nhDWrRoIeXKlWNPcCGR+nMXExNjGHYbN26ctGnTRry8vKR///6GevHx8dK/f3/5v//7vzRzJZVQKM6auXDhAs6ePYvly5fDwcEBM2bMwLVr1zB//nzMmzcPW7duRdu2bdN8XqlSpQCAB6MpZPv27ShevDhsbW2NDlLy8/ND0aJFkZSUZDgTQavVwtraGkuWLMGBAwdQpUoVpZpNL0h93cqWLWsoS/15evDgAR4+fAhbW1sAQLt27fDhhx/yRORckJSUhOvXr2PBggU4ePAgABjOW7K1tUXPnj3x66+/okePHnj8+DGePHmCli1bYt++fahTp47CrSdTybMDPrdv344333wTe/bsAQAMHToUZ8+eRXJyMj755BMA+vPTZsyYgZ07d+Kdd96BtbW1kk3XUzgImezEiROi0WhkyZIlIqLfQtrHx8ewT/7evXtFxLjX46uvvjJsMU15LzIyUvbs2SNarVZmzpwp9erVM4xj3r9/X0qUKGGY5Pgi9lzlD2vXrpVOnToZ7mc0tLJ161apVq2aPH36VAIDA6VKlSqcWJyLLly4IO3atZO2bdvKgQMHDOX/fX04DF04/fTTT2JnZyezZs0ymu9x+PBhKVmypDRs2FD8/f3l9ddfl9KlS+ernrACHUQiIiJEo9EYVsekdk0dO3ZMKlSoIK+99pqcPHnS6HM++eQTKVq0KNfJK+TGjRtSunRpqVSpkvz444+i1Wpl+vTp0qBBAxkwYICULVtWhg8fbqjPeSD5y88//yzFihUTa2trad++vaH8vxMgRUQOHTokderUkUaNGkmFChUMISS9umQeGYURnU4nCQkJMnLkSHnjjTckPj6eP1uFSExMjNSvX99wcF2q1BB6/fp1mTNnjgwbNkyCg4Pl4sWLSjQzQwU2iPz999+i0WjSrI755Zdf5MGDB3L48GEpX7689OjRw7AJ1tSpU0Wj0cjRo0eVaDKJyO+//y4qlUrq168vgYGBsmXLFkMY8fT0lBo1ahi2l+YbVv5y/fp16dq1q4wYMUI2btwoVapUkdatWxuu//f12rVrl6hUKvHz82MIyUPphZGkpCQZNmyYWFlZGe0hQoXDzZs3xcfHR/bs2SMi+t7jgnRUQoEMIteuXZPSpUtL9+7djcqnT58u7u7uhsmqBw4ckPLly0ufPn3k/fffF1tbW0MoIeX07dtXateuLW+++aY0bdpUtm3bJjqdTmbMmCH16tWTcePGGSZQFYQfIkuRkpIin332mRw8eFBE9L0j/w0jLw4DXLhwQSZMmGAIHwwheefFMPLHH3/I+PHjxc7OLl91x5P5xMTESKlSpYx2SU393RkeHi7bt283/Gzmx56wAhlEIiMjpX79+tK5c2dD4p89e7aULl1afv31VxF5/gsxLCxMSpQoIdbW1vwhVFjqFuy//PKL9OnTR3bt2iVBQUHSpEkT2bZtm2i1Wvn000+lUaNGMnjw4Hwxm5v00vvrKjEx0RBGWrVqZSi/c+eOREZGGn0+Q0jeu3DhggQGBkrJkiXF2tra6MgEKrjSCxJPnz6Vvn37SkBAgOE9MNWHH34oHTp0yNfHKahECuYU9osXL2L48OGwtraGi4sLtm3bhnXr1qFNmzZG9R4+fIjHjx8jMTERFStWVKi1lisqKgrh4eF4/fXXDWV3797Fa6+9hmHDhqF79+4YNGgQ7ty5g3HjxiEwMBCTJk3CX3/9hY0bN6JMmTLKNZ4Ms/EB4OnTpyhatCgA/SomKysrPH36FLt27cLYsWPh5eWFdevWoWPHjqhduzZWrFihZNMJwPnz5zF+/HjMmjUL1atXV7o5ZKLUn8f9+/fj4MGDiIyMRI8ePVCvXj3cuHEDH374IZKSkhAYGIjy5cvjjz/+wIYNGxAWFoaaNWsq3fyMKZuDTHP+/Hlp3bq12NnZyWeffSYixseNT5o0Sdzc3PL0OGN67tq1a1KqVClRqVTSoUMH2bRpk2HG/k8//SQBAQFy584dOXv2rAQFBUnz5s3lhx9+EK1Wa9hZlZTz4l9ec+fOlW+++cbor6rU68nJyfLLL79IlSpVRKVSSdWqVbk6Jh/ha1G4bNmyRTQajQQGBkqdOnWkbNmy0rt3b7l+/bpcvHhRRo0aJe7u7lKjRg1p1qyZ/P3330o3+aUKdBAR0W+K1aZNG2nfvr3s37/fUJ56TgknpirnypUrUq9ePfH395e6detK//79xcvLS5YvXy6bNm2SwMBA2bFjh4iInDlzRlq1aiUdOnRgcMwHXhyCuXv3rvj7+4urq6t8//33hsnEIs/DyLVr16R8+fLSuHFjzgkhMrPUn8fIyEipXLmy0Vkxa9askZYtW0qfPn0MZ6glJCTIw4cP8/VwzIsK7NDMi1KHaUQEs2fPxu7duzFlyhQcOHAAdevWVbp5Fu3ixYuYMGECdDod3n33XajVaixevBglSpTAjz/+iPr16yMsLAzW1tY4f/48ihUrhnLlyindbHpmzJgxOHbsGEqXLo0TJ04gJiYGS5cuRdeuXQ0blT1+/BgDBw7EsWPHcObMGRQtWhQpKSkoUqSIwq0nKrjWrl2L5ORk9O/f31D2zz//oGXLlti4cSMCAgIM5atXr8bEiRPx448/okGDBko01zQKByGzSZ2YVaZMGSlatChXx+Qj//zzj7Rv317atGkj58+fl8ePH8uff/4pgYGBsnbtWhHJnzO5Ld369evFwcFBjh8/LnFxcRIfHy99+/YVjUYj3333naFnJCUlRVasWMGeECIzuXPnjgQGBkrDhg1l3bp1hvKIiAjx8PAwTEh9cUJ/5cqV0xw8WVAUmiAion/D69y5s9FZM5Q/XLhwQdq0aSNt2rQx2miJ8ocZM2ak2eTo888/l0aNGkliYqLRUE2vXr3EyclJNmzYkGYYjQfYEZlHRESE9OrVS5o0aSLfffedobxjx45SoUIFuXXrlqEsMTFRAgICZPny5Uo01WSF4qyZVFWqVMHmzZs5OzwfqlSpEoKDg6FWqzF9+nQcOHBA6SbRM3///Tf2798PLy8vo/Lk5GRcvHgRRYsWhVqtRmJiIgBg8ODBePDgAUaOHIl9+/YB0K+iAQArK6s8bTtRYVW7dm2MGzcOXl5eWL58OVavXg0AWLduHZycnODv74/Nmzdjx44dmDZtGs6cOYOWLVsq2+gcKhRzRKjguHjxIkaPHo2YmBgsWrQIjRo1UrpJFu3LL7/EG2+8YTi07qeffkK5cuXg5+eH+/fv49VXX0XVqlWxefNmqNX6v1tOnDiBjRs34ubNm9i7dy/OnDmDkiVLKvllEBUqqcvjASAiIgLz58/H1atXMWjQIPTq1QtxcXF4//33cfLkSaSkpKBkyZJYuXJlwT3AUOkuGbI8586dk65du8rVq1eVbopFu3z5spQtW1YGDhwoJ0+elDt37ohGo5FevXrJqVOnRERk06ZN8sorr0jbtm3l7NmzcuTIEWnfvr28//77cv36dSlZsqSsX79e4a+EqHBInSuXOv8qdUg0IiJC3n77bfH39zfMqxMRuXjxoly7dk3u3buX9401I/aIkCKSk5Pzx/HTFu7EiRMYOHAgateujYULF+Lvv//Ge++9h4CAAEyePBnly5fHr7/+imnTpuHs2bMoVaoUXFxccOjQITx48ABNmjTBsmXLCmyXMFF+Ic82K/v111+xdOlSPHnyBPb29obN6M6ePYsZM2bg2rVrGDhwIN59912lm2w2hWqOCBUcDCH5Q506dfD1118jPDwco0aNQo0aNfDdd9/hjz/+wKeffopLly6hY8eOOHLkCPbs2YPffvsNhw8fRpEiRbBo0SIUKVIEVatWVfrLICrwVCoVfv75Z7z++uvw9fVF/fr18eTJEzRq1AhbtmyBr68vxo8fj/Lly2PevHn44YcflG6y2bBHhIhw4sQJ9O3bF35+fvjss89w9uxZvP3222jRogVGjRqF2rVrG+oeP34cK1aswMaNG/HHH3/glVdeUa7hRAWQvHB0AgDodDokJiaiU6dOaNCgAWbPnm24NnjwYKxbtw7Hjh1DlSpVcOzYMXz99df4+OOP4e3trUDrzY89IkSEOnXq4Ntvv8Xx48cxduxY+Pr6YsOGDQgNDcWUKVNw+fJlQ12tVgt3d3ccOnSIIYQoB1QqFe7evYt79+4BANRqNVJSUnD79m34+PgA0J/tBADLli2Dn58fpk+fDhFBvXr1EBwcXGhCCMAgQkTPvBhGxo0bh+rVq+Pbb7+FWq02+qVXv359fPTRR6hWrZpyjSUqoEQEjx8/RrVq1TBp0iTExMQAABwcHODu7o6QkBAAQNGiRQ1hpHLlykhISDD0ohS2oW0GESIySA0jERER6NevH+rXr4+QkBCo1WrodDpDvdRTeIkoe1QqFYoXL47Fixfj22+/xZw5c3D79m0AQP/+/XHnzh189NFHAJ7/nCUnJ6NYsWJ4+vQpCuNsCh4GQURG6tSpg6VLl2Lp0qXQaDSG8tR9RIjINCKCXr16wdbWFt27d0fRokUxfvx4BAYG4vz589i8eTP++usvtGnTBufPn0dISAgOHz5caP8A4GRVIkpX6oQ6nU7HEEKUQ//9+UlJSQEAw6GQ3bt3x9atWzFy5EjMmDEDOp0Oe/bswcqVK3Hv3j2UKVMGU6dORc2aNRVpf15gECGiDP13dj8RZd/ly5cxZ84cfP311wCeh5PZs2fj888/x/vvv4+5c+dixIgR+PTTT2Fvbw9APySjUqkKbU9IKg7NEFGGGEKITPP06VP8/fffWL9+PZ48eYL169dDrVZj1qxZWLBgAb7//nu0bdsWfn5+6NGjB4oWLYpRo0bBzc2t0E1KzQiDCBERkZktXboUbdq0QcWKFdGiRQusWrUKY8eORf/+/VGjRg0sWrQI69atQ9u2bSEi6NatG1QqFbp37w4bGxtMmzbNYoZEOTRDRERkRrdu3UKXLl1w8+ZNhIaGonz58oiLi8OOHTvwySef4PLlywgNDUVAQABSUlIMB9ypVCr8+OOPqFSpEnx9fRX+KvIOgwgREZGZHT16FJMnT8Y///yDvXv3okKFCoiNjcWOHTswadIkNG7cGOvWrQOANGHE0jCIEBERmYlWqzWEioMHD2LGjBm4cuUKdu3aBU9PT0PPyPjx49GkSRNs2LAhzedZGssYgCIiIsoDqfM6fv31VyxYsADx8fE4f/48WrZsiX///RcODg7o0KED5s+fjyNHjqBDhw4AYLEhBGAQISIiMhuVSoXQ0FAEBgaiVatW+Oyzz7BixQo4OzujVatWuHz5siGMTJkyBVFRUbhx44bSzVYUh2aIiIhyKCwsDAEBAUZlM2fOxMGDB7Fjxw5D2aFDhzBq1Cg8ePAAe/bsgaenJx49egQAhn1DLBV7RIiIiHLg999/R8eOHRETE2N0BkxycjJOnTplOLQOABo3bozevXvj0qVLqFu3Li5fvgx7e3uLDyEAgwgREVGONG7cGJcuXULp0qVx7do1Q/lrr72GUqVKYc2aNYiPjzeUV69eHS1btkTbtm2h1WqVaHK+xCBCRESUA7a2tihTpgwiIyPh4+ODzz77DAAQEBCAqlWrYuXKlfjuu+/w5MkTaLVa7N69G87Ozli+fDkqVaqkcOvzD84RISIiMkFKSgpmzpyJWbNmYc6cORg1ahQSEhLQr18/nDt3DteuXUO1atVw4sQJHD58uFAfYJcT3OKdiIgoG1IPgzx37hzu3bsHLy8vTJkyBcWLF8eYMWMgIhg9ejRWr16NEydO4MCBA7C1tcWqVavYE5IOBhEiIqJsUKlU2LZtG3r16gUXFxfcuHEDwcHB6N27N9RqNcaMGQMAGD16NBo2bIiGDRsq3OL8jUGEiIgoi3Q6HWJjY/HZZ59h4cKFaNGiBTZt2oSBAwfi3r17eO+99wAAEydORHJyMiZMmKBwi/M/BhEiIqKXSB2OSU5Ohq2tLZo2bYpu3bqhZMmSmDRpEooXL45Ro0YBAN577z0kJCRg/vz5+OCDD1CyZEmFW5+/MYgQERG9ROrJuMuWLcO1a9cgIujRo4chZIwYMQIAMH78eCQkJGDw4MEYNGgQQ0gWcPkuERHRSxw7dgzvvvsuypcvj4YNG+Lff//Ft99+i6tXrxrqjBgxAtOmTcOSJUtQpEgRODk5KdjigoPLd4mIiDLx77//Yu3atbCzszPM+Vi2bBlmzZqFXr16YdCgQfDy8jLUf/DgAXtCsoFDM0RERBmIi4vDW2+9hStXrmDgwIGG8sGDB0On02H27NmwsrJCv3794OPjAwAoUaKEQq0tmDg0Q0RElAEHBwd8/fXXKFmyJEJDQ3H69GnDtaFDh+KTTz7BggUL8N133yElJQWAfj4JZR2HZoiIiF7i5MmTeO+999CgQQMMHz4c1atXN1xbuXIlXnvtNW5WlkMMIkRERFlw4sQJ9O/fH35+fhg1ahR8fX2VblKhwCBCRESURSdOnMCgQYNQvnx5TJkyBVWrVlW6SQUe54gQERFlUZ06dRAcHIzo6Gg4Ojoq3ZxCgT0iRERE2ZSYmAhbW1ulm1EoMIgQERGRYjg0Q0RERIphECEiIiLFMIgQERGRYhhEiIiISDEMIkRERKQYBhEiIiJSDIMIERERKYZBhIiIiBTDIEJERESKYRAhIiIixfw/F5j8UcRcE64AAAAASUVORK5CYII=",
      "text/plain": [
       "<Figure size 640x480 with 1 Axes>"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    }
   ],
   "source": [
    "# replicate IPCC fig 7.19\n",
    "paleo_sat_avgs = pd.read_csv('observational_data/paleo/processed/annual_mean_global_obs.csv')\n",
    "\n",
    "fig, ax = plt.subplots()\n",
    "\n",
    "ax.errorbar(np.arange(1,6), paleo_sat_avgs['mean temperature [degreesC]'], yerr=paleo_sat_avgs['error [degreesC]'], fmt='o',label='Observations')\n",
    "plt.scatter(x=annual_paleo_results['Time Period idx'] + 1.2,y=annual_paleo_results['tas'],label='Models',color='orange')\n",
    "\n",
    "ax.set_xticks(np.arange(1,6))\n",
    "ax.set_xticklabels(paleo_sat_avgs['Time Period'],rotation=45);\n",
    "ax.legend()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 51,
   "id": "86b0ec03",
   "metadata": {},
   "outputs": [],
   "source": [
    "annual_paleo_obs = paleo_sat_avgs.rename(columns={'Time Period':'period','mean temperature [degreesC]':'tas_obs'})[['period','tas_obs']]\n",
    "annual_paleo_obs['period'] = ['eocene','midPliocene-eoi400','lig127k','lgm','midHolocene']\n",
    "\n",
    "mae_results = annual_paleo_results.rename(columns={'tas':'tas_anom'}).merge(annual_paleo_obs)\n",
    "mae_results['mae'] = (mae_results['tas_anom'] - mae_results['tas_obs']).abs()\n",
    "mae_results.to_csv('/Users/willatobin/Documents/SIO/ClimateBench2/backend/results/paleo/annual_zonal_means.csv')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "aed87b54",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "backend_env",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
